CREATE OR REPLACE VIEW dga_stage_manager_deal_memo_get_list(
    dga_stage_manager_deal_memo_id,
    dga_stage_manager_deal_memo_contact_id,
    -- dga_stage_manager_memo_contact_name,
    dga_stage_manager_deal_memo_contact_first_name,
    dga_stage_manager_deal_memo_contact_middle_name,
    dga_stage_manager_deal_memo_contact_last_name,
    dga_stage_manager_deal_memo_contact_suffix,
    dga_stage_manager_deal_memo_contact_full_name,
    dga_stage_manager_memo_contact_address,
    dga_stage_manager_memo_contact_city,
    dga_stage_manager_memo_contact_state_code,
    dga_stage_manager_memo_contact_state_name,
    dga_stage_manager_memo_contact_phone,
    dga_stage_manager_memo_contact_email,
    dga_stage_manager_deal_memo_ssn,
    dga_stage_manager_deal_memo_loanout,
    dga_stage_manager_deal_memo_fid,
    dga_stage_manager_deal_memo_salary,
    dga_stage_manager_deal_memo_salary_period_id,
    dga_stage_manager_deal_memo_salary_period_name,
    dga_stage_manager_deal_memo_salary_period_period,
    dga_stage_manager_deal_memo_salary_period_plural,
    dga_stage_manager_deal_memo_aditional_time,
    dga_stage_manager_deal_memo_aditional_time_period_id,
    dga_stage_manager_deal_memo_aditional_time_period_name,
    dga_stage_manager_deal_memo_aditional_time_period_period,
    dga_stage_manager_deal_memo_aditional_time_period_plural,
    dga_stage_manager_deal_memo_start_date,
    dga_stage_manager_deal_memo_guaranteed,
    dga_stage_manager_deal_memo_guaranteed_period_id,
    dga_stage_manager_deal_memo_guaranteed_period_name,
    dga_stage_manager_deal_memo_guaranteed_period_period,
    dga_stage_manager_deal_memo_guaranteed_period_plural,
    dga_stage_manager_deal_memo_production_id,
    dga_stage_manager_deal_memo_production_title,
    dga_stage_manager_deal_memo_episode_id,
    dga_stage_manager_deal_memo_episode_title,
    dga_stage_manager_deal_memo_episode_episode_number,
    dga_stage_manager_deal_memo_episode_episode_abreviation,
    dga_stage_manager_deal_memo_category_associate_director,
    dga_stage_manager_deal_memo_category_stage_manager,
    dga_stage_manager_deal_memo_category_aditional_stage_manager,
    dga_stage_manager_deal_memo_prime_time_per_week_studio,
    dga_stage_manager_deal_memo_prime_time_per_week_location,
    dga_stage_manager_deal_memo_prime_time_per_day_studio,
    dga_stage_manager_deal_memo_prime_time_per_day_location,
    dga_stage_manager_deal_memo_other_per_week_40,
    dga_stage_manager_deal_memo_other_per_week_flat_60,
    dga_stage_manager_deal_memo_other_per_day_8,
    dga_stage_manager_deal_memo_other_per_day_flat_12,
    dga_stage_manager_deal_memo_project_info_30_lower,
    dga_stage_manager_deal_memo_project_info_30_between,
    dga_stage_manager_deal_memo_project_info_30_higher,
    dga_stage_manager_deal_memo_project_info_60_lower,
    dga_stage_manager_deal_memo_project_info_60_between,
    dga_stage_manager_deal_memo_project_info_60_higher,
    dga_stage_manager_deal_memo_project_info_120_lower,
    dga_stage_manager_deal_memo_project_info_120_between,
    dga_stage_manager_deal_memo_project_info_120_higher,
    dga_stage_manager_deal_memo_other_conditions,
    dga_stage_manager_deal_memo_employer_name,
    dga_stage_manager_deal_memo_employee_name,
    dga_stage_manager_deal_memo_employee_date,
    dga_stage_manager_deal_memo_signatory,
    dga_stage_manager_deal_memo_signatory_by,
    dga_stage_manager_deal_memo_signatory_date,
    dga_stage_manager_deal_memo_created,
    dga_stage_manager_deal_memo_created_by,
    dga_stage_manager_deal_memo_updated,
    dga_stage_manager_deal_memo_updated_by,
    dga_stage_manager_deal_memo_status
) AS
    SELECT dga_stage_manager_deal_memo.id                                                            AS dga_stage_manager_deal_memo_id,
           dga_stage_manager_deal_memo.contact_id                                                    AS dga_stage_manager_deal_memo_contact_id,
        --    contact.name                                                                              AS dga_stage_manager_memo_contact_name,
           contact.first_name                                                                        AS dga_stage_manager_deal_memo_contact_first_name,
           contact.middle_name                                                                       AS dga_stage_manager_deal_memo_contact_middle_name,
           contact.last_name                                                                         AS dga_stage_manager_deal_memo_contact_last_name,
           contact.suffix                                                                            AS dga_stage_manager_deal_memo_contact_suffix,
           contact_get_full_name(contact.id)                                                         AS dga_stage_manager_deal_memo_contact_full_name,
           contact.address                                                                           AS dga_stage_manager_memo_contact_address,
           contact.city                                                                              AS dga_stage_manager_memo_contact_city,
           contact.state_code                                                                        AS dga_stage_manager_memo_contact_state_code,
           state.name                                                                                AS dga_stage_manager_memo_contact_state_name,
           contact.phone                                                                             AS dga_stage_manager_memo_contact_phone,
           contact.email                                                                             AS dga_stage_manager_memo_contact_email,
           dga_stage_manager_deal_memo.ssn                                                           AS dga_stage_manager_deal_memo_ssn,
           dga_stage_manager_deal_memo.loanout                                                       AS dga_stage_manager_deal_memo_loanout,
           dga_stage_manager_deal_memo.fid                                                           AS dga_stage_manager_deal_memo_fid,
           dga_stage_manager_deal_memo.salary                                                        AS dga_stage_manager_deal_memo_salary,
           dga_stage_manager_deal_memo.salary_period_id                                              AS dga_stage_manager_deal_memo_salary_period_id,
           salary_period.name                                                                        AS dga_stage_manager_deal_memo_salary_period_name,
           salary_period.period                                                                      AS dga_stage_manager_deal_memo_salary_period_period,
           salary_period.plural                                                                      AS dga_stage_manager_deal_memo_salary_period_plural,
           dga_stage_manager_deal_memo.aditional_time                                                AS dga_stage_manager_deal_memo_aditional_time,
           dga_stage_manager_deal_memo.aditional_time_period_id                                      AS dga_stage_manager_deal_memo_aditional_time_period_id,
           aditional_time_period.name                                                                AS dga_stage_manager_deal_memo_aditional_time_period_name,
           aditional_time_period.period                                                              AS dga_stage_manager_deal_memo_aditional_time_period_period,
           aditional_time_period.plural                                                              AS dga_stage_manager_deal_memo_aditional_time_period_plural,
           dga_stage_manager_deal_memo.start_date                                                    AS dga_stage_manager_deal_memo_start_date,
           dga_stage_manager_deal_memo.guaranteed                                                    AS dga_stage_manager_deal_memo_guaranteed,
           dga_stage_manager_deal_memo.guaranteed_period_id                                          AS dga_stage_manager_deal_memo_guaranteed_period_id,
           guaranteed_period.name                                                                    AS dga_stage_manager_deal_memo_guaranteed_period_name,
           guaranteed_period.period                                                                  AS dga_stage_manager_deal_memo_guaranteed_period_period,
           guaranteed_period.plural                                                                  AS dga_stage_manager_deal_memo_guaranteed_period_plural,
           dga_stage_manager_deal_memo.production_id                                                 AS dga_stage_manager_deal_memo_production_id,
           production.title                                                                          AS dga_stage_manager_deal_memo_production_title,
           dga_stage_manager_deal_memo.episode_id                                                    AS dga_stage_manager_deal_memo_episode_id,
           episode.title                                                                             AS dga_stage_manager_deal_memo_episode_title,
           LPAD(episode.episode_number, 2, 0)                                                        AS dga_stage_manager_deal_memo_episode_episode_number,
           CONCAT('S', LPAD(season.season_number, 2, 0), 'E', LPAD(episode.episode_number, 2, 0))    AS dga_stage_manager_deal_memo_episode_episode_abreviation,
           dga_stage_manager_deal_memo.category_associate_director                                   AS dga_stage_manager_deal_memo_category_associate_director,
           dga_stage_manager_deal_memo.category_stage_manager                                        AS dga_stage_manager_deal_memo_category_stage_manager,
           dga_stage_manager_deal_memo.category_aditional_stage_manager                              AS dga_stage_manager_deal_memo_category_aditional_stage_manager,
           dga_stage_manager_deal_memo.prime_time_per_week_studio                                    AS dga_stage_manager_deal_memo_prime_time_per_week_studio,
           dga_stage_manager_deal_memo.prime_time_per_week_location                                  AS dga_stage_manager_deal_memo_prime_time_per_week_location,
           dga_stage_manager_deal_memo.prime_time_per_day_studio                                     AS dga_stage_manager_deal_memo_prime_time_per_day_studio,
           dga_stage_manager_deal_memo.prime_time_per_day_location                                   AS dga_stage_manager_deal_memo_prime_time_per_day_location,
           dga_stage_manager_deal_memo.other_per_week_40                                             AS dga_stage_manager_deal_memo_other_per_week_40,
           dga_stage_manager_deal_memo.other_per_week_flat_60                                        AS dga_stage_manager_deal_memo_other_per_week_flat_60,
           dga_stage_manager_deal_memo.other_per_day_8                                               AS dga_stage_manager_deal_memo_other_per_day_8,
           dga_stage_manager_deal_memo.other_per_day_flat_12                                         AS dga_stage_manager_deal_memo_other_per_day_flat_12,
           dga_stage_manager_deal_memo.project_info_30_lower                                         AS dga_stage_manager_deal_memo_project_info_30_lower,
           dga_stage_manager_deal_memo.project_info_30_between                                       AS dga_stage_manager_deal_memo_project_info_30_between,
           dga_stage_manager_deal_memo.project_info_30_higher                                        AS dga_stage_manager_deal_memo_project_info_30_higher,
           dga_stage_manager_deal_memo.project_info_60_lower                                         AS dga_stage_manager_deal_memo_project_info_60_lower,
           dga_stage_manager_deal_memo.project_info_60_between                                       AS dga_stage_manager_deal_memo_project_info_60_between,
           dga_stage_manager_deal_memo.project_info_60_higher                                        AS dga_stage_manager_deal_memo_project_info_60_higher,
           dga_stage_manager_deal_memo.project_info_120_lower                                        AS dga_stage_manager_deal_memo_project_info_120_lower,
           dga_stage_manager_deal_memo.project_info_120_between                                      AS dga_stage_manager_deal_memo_project_info_120_between,
           dga_stage_manager_deal_memo.project_info_120_higher                                       AS dga_stage_manager_deal_memo_project_info_120_higher,
           dga_stage_manager_deal_memo.other_conditions                                              AS dga_stage_manager_deal_memo_other_conditions,
           dga_stage_manager_deal_memo.employer_name                                                 AS dga_stage_manager_deal_memo_employer_name,
           dga_stage_manager_deal_memo.employee_name                                                 AS dga_stage_manager_deal_memo_employee_name,
           dga_stage_manager_deal_memo.employee_date                                                 AS dga_stage_manager_deal_memo_employee_date,
           dga_stage_manager_deal_memo.signatory                                                     AS dga_stage_manager_deal_memo_signatory,
           dga_stage_manager_deal_memo.signatory_by                                                  AS dga_stage_manager_deal_memo_signatory_by,
           dga_stage_manager_deal_memo.signatory_date                                                AS dga_stage_manager_deal_memo_signatory_date,
           DATE_FORMAT(dga_stage_manager_deal_memo.created,'%m/%d/%Y %H:%i:%S')                      AS dga_stage_manager_deal_memo_created,
           dga_stage_manager_deal_memo.created_by                                                    AS dga_stage_manager_deal_memo_created_by,
           DATE_FORMAT(dga_stage_manager_deal_memo.updated,'%m/%d/%Y %H:%i:%S')                      AS dga_stage_manager_deal_memo_updated,
           dga_stage_manager_deal_memo.updated_by                                                    AS dga_stage_manager_deal_memo_updated_by,
           dga_stage_manager_deal_memo.status                                                        AS dga_stage_manager_deal_memo_status
      FROM dga_stage_manager_deal_memo AS dga_stage_manager_deal_memo INNER JOIN contact    AS contact               ON contact.id               = dga_stage_manager_deal_memo.contact_id
                                                                      LEFT  JOIN state      AS state                 ON state.code               = contact.state_code
                                                                      LEFT  JOIN period     AS salary_period         ON salary_period.id         = dga_stage_manager_deal_memo.salary_period_id
                                                                      LEFT  JOIN period     AS aditional_time_period ON aditional_time_period.id = dga_stage_manager_deal_memo.aditional_time_period_id
                                                                      LEFT  JOIN period     AS guaranteed_period     ON guaranteed_period.id     = dga_stage_manager_deal_memo.guaranteed_period_id
                                                                      INNER JOIN production AS production            ON production.id            = dga_stage_manager_deal_memo.production_id
                                                                      INNER JOIN episode    AS episode               ON episode.id               = dga_stage_manager_deal_memo.episode_id
                                                                      INNER JOIN season     AS season                ON episode.season_id        = season.id;;