CREATE OR REPLACE VIEW dga_pif_tv_get_list(
    dga_pif_tv_id,
    dga_pif_tv_company_id,
    dga_pif_tv_company_name,
    dga_pif_tv_contact_id,
    dga_pif_tv_production_id,
    dga_pif_tv_production_title,
    dga_pif_tv_copyright_holder,
    dga_pif_tv_copyright_holder_name,
    dga_pif_tv_copyright_holder_phone,
    dga_pif_tv_budget,
    dga_pif_tv_locations,
    dga_pif_tv_date_pre_production,
    dga_pif_tv_date_principal_photography,
    dga_pif_tv_date_wrap,
    dga_pif_tv_format_multi_camera,
    dga_pif_tv_format_single_camera,
    dga_pif_tv_produced_digital,
    dga_pif_tv_produced_film,
    dga_pif_tv_produced_tape,
    dga_pif_tv_produced_live,
    dga_pif_tv_produced_other,
    dga_pif_tv_produced_other_description,
    dga_pif_tv_program_type_dramatic,
    dga_pif_tv_program_type_sitcom,
    dga_pif_tv_program_type_reality,
    dga_pif_tv_program_type_variety,
    dga_pif_tv_program_type_other,
    dga_pif_tv_program_type_other_description,
    dga_pif_tv_program_length_30,
    dga_pif_tv_program_length_60,
    dga_pif_tv_program_length_90,
    dga_pif_tv_program_length_120,
    dga_pif_tv_program_length_other,
    dga_pif_tv_program_length_other_description,
    dga_pif_tv_network,
    dga_pif_tv_network_abc,
    dga_pif_tv_network_cbs,
    dga_pif_tv_network_fox,
    dga_pif_tv_network_nbc,
    dga_pif_tv_network_pbs,
    dga_pif_tv_network_upn,
    dga_pif_tv_network_wb,
    dga_pif_tv_network_syndication,
    dga_pif_tv_basic_cable,
    dga_pif_tv_basic_cable_a_and_e,
    dga_pif_tv_basic_cable_disney,
    dga_pif_tv_basic_cable_lifetime,
    dga_pif_tv_basic_cable_mtv,
    dga_pif_tv_basic_cable_nickelodeon,
    dga_pif_tv_basic_cable_tnt,
    dga_pif_tv_basic_cable_usa,
    dga_pif_tv_basic_cable_other,
    dga_pif_tv_basic_cable_other_description,
    dga_pif_tv_pay_tv,
    dga_pif_tv_pay_tv_hbo,
    dga_pif_tv_pay_tv_showtime,
    dga_pif_tv_pay_tv_tmc,
    dga_pif_tv_pay_tv_starz,
    dga_pif_tv_pay_tv_cinemax,
    dga_pif_tv_pay_tv_other,
    dga_pif_tv_pay_tv_other_description,
    dga_pif_tv_pilot,
    dga_pif_tv_direct_to_video,
    dga_pif_tv_other,
    dga_pif_tv_other_description,
    dga_pif_tv_employee_info_director_name,
    dga_pif_tv_employee_info_1_name,
    dga_pif_tv_employee_info_1_upm,
    dga_pif_tv_employee_info_1_associate_director,
    dga_pif_tv_employee_info_2_name,
    dga_pif_tv_employee_info_2_first_assistant_director,
    dga_pif_tv_employee_info_2_stage_manager,
    dga_pif_tv_employee_info_3_name,
    dga_pif_tv_employee_info_3_key_second_assistant_director,
    dga_pif_tv_employee_info_3_second_stage_manager,
    dga_pif_tv_employee_info_4_name,
    dga_pif_tv_employee_info_4_second_assistant_director,
    dga_pif_tv_employee_info_4_third_stage_manager,
    dga_pif_tv_employee_info_5_name,
    dga_pif_tv_employee_info_5_add_second_assistant_director,
    dga_pif_tv_employee_info_5_production_associate,
    dga_pif_tv_employee_info_6_name,
    dga_pif_tv_employee_info_6_associate_director,
    dga_pif_tv_employee_info_7_name,
    dga_pif_tv_employee_info_7_associate_director_line_cut,
    dga_pif_tv_employee_info_other_description,
    dga_pif_tv_affiliations_sav,
    dga_pif_tv_affiliations_wga,
    dga_pif_tv_affiliations_dcg,
    dga_pif_tv_affiliations_aftra,
    dga_pif_tv_affiliations_iatse,
    dga_pif_tv_affiliations_nabet,
    dga_pif_tv_affiliations_afm,
    dga_pif_tv_affiliations_actra,
    dga_pif_tv_affiliations_other,
    dga_pif_tv_affiliations_other_description,
    dga_pif_tv_employment_contact_name,
    dga_pif_tv_employment_contacr_phone,
    dga_pif_tv_residuals_contact_name,
    dga_pif_tv_residuals_contacr_phone,
    dga_pif_tv_primary_finance_source,
    dga_pif_tv_primary_finance_contact,
    dga_pif_tv_primary_finance_phone,
    dga_pif_tv_completion_bond_company,
    dga_pif_tv_completion_bond_contact,
    dga_pif_tv_completion_bond_phone,
    dga_pif_tv_payroll_company,
    dga_pif_tv_payroll_contact,
    dga_pif_tv_payroll_phone,
    dga_pif_tv_credit_line,
    dga_pif_tv_credit_line_bank,
    dga_pif_tv_credit_line_contact,
    dga_pif_tv_credit_line_phone,
    dga_pif_tv_foreign_distribuitors,
    dga_pif_tv_domestic_distribuitors,
    dga_pif_tv_signature,
    dga_pif_tv_signature_title,
    dga_pif_tv_signature_print_name,
    dga_pif_tv_signature_phone,
    dga_pif_tv_signature_date,
    dga_pif_tv_created,
    dga_pif_tv_created_by,
    dga_pif_tv_updated,
    dga_pif_tv_updated_by,
    dga_pif_tv_status
) AS
    SELECT dga_pif_tv.id                                                 AS dga_pif_tv_id,
           dga_pif_tv.company_id                                         AS dga_pif_tv_company_id,
           company.name                                                  AS dga_pif_tv_company_name,
           dga_pif_tv.contact_id                                         AS dga_pif_tv_contact_id,
           dga_pif_tv.production_id                                      AS dga_pif_tv_production_id,
           production.title                                              AS dga_pif_tv_production_title,
           dga_pif_tv.copyright_holder                                   AS dga_pif_tv_copyright_holder,
           dga_pif_tv.copyright_holder_name                              AS dga_pif_tv_copyright_holder_name,
           dga_pif_tv.copyright_holder_phone                             AS dga_pif_tv_copyright_holder_phone,
           dga_pif_tv.budget                                             AS dga_pif_tv_budget,
           dga_pif_tv.locations                                          AS dga_pif_tv_locations,
           DATE_FORMAT(dga_pif_tv.date_pre_production,'%m/%d/%Y')        AS dga_pif_tv_date_pre_production,
           DATE_FORMAT(dga_pif_tv.date_principal_photography,'%m/%d/%Y') AS dga_pif_tv_date_principal_photography,
           DATE_FORMAT(dga_pif_tv.date_wrap,'%m/%d/%Y')                  AS dga_pif_tv_date_wrap,
           dga_pif_tv.format_multi_camera                                AS dga_pif_tv_format_multi_camera,
           dga_pif_tv.format_single_camera                               AS dga_pif_tv_format_single_camera,
           dga_pif_tv.produced_digital                                   AS dga_pif_tv_produced_digital,
           dga_pif_tv.produced_film                                      AS dga_pif_tv_produced_film,
           dga_pif_tv.produced_tape                                      AS dga_pif_tv_produced_tape,
           dga_pif_tv.produced_live                                      AS dga_pif_tv_produced_live,
           dga_pif_tv.produced_other                                     AS dga_pif_tv_produced_other,
           dga_pif_tv.produced_other_description                         AS dga_pif_tv_produced_other_description,
           dga_pif_tv.program_type_dramatic                              AS dga_pif_tv_program_type_dramatic,
           dga_pif_tv.program_type_sitcom                                AS dga_pif_tv_program_type_sitcom,
           dga_pif_tv.program_type_reality                               AS dga_pif_tv_program_type_reality,
           dga_pif_tv.program_type_variety                               AS dga_pif_tv_program_type_variety,
           dga_pif_tv.program_type_other                                 AS dga_pif_tv_program_type_other,
           dga_pif_tv.program_type_other_description                     AS dga_pif_tv_program_type_other_description,
           dga_pif_tv.program_length_30                                  AS dga_pif_tv_program_length_30,
           dga_pif_tv.program_length_60                                  AS dga_pif_tv_program_length_60,
           dga_pif_tv.program_length_90                                  AS dga_pif_tv_program_length_90,
           dga_pif_tv.program_length_120                                 AS dga_pif_tv_program_length_120,
           dga_pif_tv.program_length_other                               AS dga_pif_tv_program_length_other,
           dga_pif_tv.program_length_other_description                   AS dga_pif_tv_program_length_other_description,
           dga_pif_tv.network                                            AS dga_pif_tv_network,
           dga_pif_tv.network_abc                                        AS dga_pif_tv_network_abc,
           dga_pif_tv.network_cbs                                        AS dga_pif_tv_network_cbs,
           dga_pif_tv.network_fox                                        AS dga_pif_tv_network_fox,
           dga_pif_tv.network_nbc                                        AS dga_pif_tv_network_nbc,
           dga_pif_tv.network_pbs                                        AS dga_pif_tv_network_pbs,
           dga_pif_tv.network_upn                                        AS dga_pif_tv_network_upn,
           dga_pif_tv.network_wb                                         AS dga_pif_tv_network_wb,
           dga_pif_tv.network_syndication                                AS dga_pif_tv_network_syndication,
           dga_pif_tv.basic_cable                                        AS dga_pif_tv_basic_cable,
           dga_pif_tv.basic_cable_a_and_e                                AS dga_pif_tv_basic_cable_a_and_e,
           dga_pif_tv.basic_cable_disney                                 AS dga_pif_tv_basic_cable_disney,
           dga_pif_tv.basic_cable_lifetime                               AS dga_pif_tv_basic_cable_lifetime,
           dga_pif_tv.basic_cable_mtv                                    AS dga_pif_tv_basic_cable_mtv,
           dga_pif_tv.basic_cable_nickelodeon                            AS dga_pif_tv_basic_cable_nickelodeon,
           dga_pif_tv.basic_cable_tnt                                    AS dga_pif_tv_basic_cable_tnt,
           dga_pif_tv.basic_cable_usa                                    AS dga_pif_tv_basic_cable_usa,
           dga_pif_tv.basic_cable_other                                  AS dga_pif_tv_basic_cable_other,
           dga_pif_tv.basic_cable_other_description                      AS dga_pif_tv_basic_cable_other_description,
           dga_pif_tv.pay_tv                                             AS dga_pif_tv_pay_tv,
           dga_pif_tv.pay_tv_hbo                                         AS dga_pif_tv_pay_tv_hbo,
           dga_pif_tv.pay_tv_showtime                                    AS dga_pif_tv_pay_tv_showtime,
           dga_pif_tv.pay_tv_tmc                                         AS dga_pif_tv_pay_tv_tmc,
           dga_pif_tv.pay_tv_starz                                       AS dga_pif_tv_pay_tv_starz,
           dga_pif_tv.pay_tv_cinemax                                     AS dga_pif_tv_pay_tv_cinemax,
           dga_pif_tv.pay_tv_other                                       AS dga_pif_tv_pay_tv_other,
           dga_pif_tv.pay_tv_other_description                           AS dga_pif_tv_pay_tv_other_description,
           dga_pif_tv.direct_to_video                                    AS dga_pif_tv_direct_to_video,
           dga_pif_tv.other                                              AS dga_pif_tv_other,
           dga_pif_tv.other_description                                  AS dga_pif_tv_other_description,
           dga_pif_tv.pilot                                              AS dga_pif_tv_pilot,
           dga_pif_tv.employee_info_director_name                        AS dga_pif_tv_employee_info_director_name,
           dga_pif_tv.employee_info_1_name                               AS dga_pif_tv_employee_info_1_name,
           dga_pif_tv.employee_info_1_upm                                AS dga_pif_tv_employee_info_1_upm,
           dga_pif_tv.employee_info_1_associate_director                 AS dga_pif_tv_employee_info_1_associate_director,
           dga_pif_tv.employee_info_2_name                               AS dga_pif_tv_employee_info_2_name,
           dga_pif_tv.employee_info_2_first_assistant_director           AS dga_pif_tv_employee_info_2_first_assistant_director,
           dga_pif_tv.employee_info_2_stage_manager                      AS dga_pif_tv_employee_info_2_stage_manager,
           dga_pif_tv.employee_info_3_name                               AS dga_pif_tv_employee_info_3_name,
           dga_pif_tv.employee_info_3_key_second_assistant_director      AS dga_pif_tv_employee_info_3_key_second_assistant_director,
           dga_pif_tv.employee_info_3_second_stage_manager               AS dga_pif_tv_employee_info_3_second_stage_manager,
           dga_pif_tv.employee_info_4_name                               AS dga_pif_tv_employee_info_4_name,
           dga_pif_tv.employee_info_4_second_assistant_director          AS dga_pif_tv_employee_info_4_second_assistant_director,
           dga_pif_tv.employee_info_4_third_stage_manager                AS dga_pif_tv_employee_info_4_third_stage_manager,
           dga_pif_tv.employee_info_5_name                               AS dga_pif_tv_employee_info_5_name,
           dga_pif_tv.employee_info_5_add_second_assistant_director      AS dga_pif_tv_employee_info_5_add_second_assistant_director,
           dga_pif_tv.employee_info_5_production_associate               AS dga_pif_tv_employee_info_5_production_associate,
           dga_pif_tv.employee_info_6_name                               AS dga_pif_tv_employee_info_6_name,
           dga_pif_tv.employee_info_6_associate_director                 AS dga_pif_tv_employee_info_6_associate_director,
           dga_pif_tv.employee_info_7_name                               AS dga_pif_tv_employee_info_7_name,
           dga_pif_tv.employee_info_7_associate_director_line_cut        AS dga_pif_tv_employee_info_7_associate_director_line_cut,
           dga_pif_tv.employee_info_other_description                    AS dga_pif_tv_employee_info_other_description,
           dga_pif_tv.affiliations_sav                                   AS dga_pif_tv_affiliations_sav,
           dga_pif_tv.affiliations_wga                                   AS dga_pif_tv_affiliations_wga,
           dga_pif_tv.affiliations_dcg                                   AS dga_pif_tv_affiliations_dcg,
           dga_pif_tv.affiliations_aftra                                 AS dga_pif_tv_affiliations_aftra,
           dga_pif_tv.affiliations_iatse                                 AS dga_pif_tv_affiliations_iatse,
           dga_pif_tv.affiliations_nabet                                 AS dga_pif_tv_affiliations_nabet,
           dga_pif_tv.affiliations_afm                                   AS dga_pif_tv_affiliations_afm,
           dga_pif_tv.affiliations_actra                                 AS dga_pif_tv_affiliations_actra,
           dga_pif_tv.affiliations_other                                 AS dga_pif_tv_affiliations_other,
           dga_pif_tv.affiliations_other_description                     AS dga_pif_tv_affiliations_other_description,
           dga_pif_tv.employment_contact_name                            AS dga_pif_tv_employment_contact_name,
           dga_pif_tv.employment_contacr_phone                           AS dga_pif_tv_employment_contacr_phone,
           dga_pif_tv.residuals_contact_name                             AS dga_pif_tv_residuals_contact_name,
           dga_pif_tv.residuals_contacr_phone                            AS dga_pif_tv_residuals_contacr_phone,
           dga_pif_tv.primary_finance_source                             AS dga_pif_tv_primary_finance_source,
           dga_pif_tv.primary_finance_contact                            AS dga_pif_tv_primary_finance_contact,
           dga_pif_tv.primary_finance_phone                              AS dga_pif_tv_primary_finance_phone,
           dga_pif_tv.completion_bond_company                            AS dga_pif_tv_completion_bond_company,
           dga_pif_tv.completion_bond_contact                            AS dga_pif_tv_completion_bond_contact,
           dga_pif_tv.completion_bond_phone                              AS dga_pif_tv_completion_bond_phone,
           dga_pif_tv.payroll_company                                    AS dga_pif_tv_payroll_company,
           dga_pif_tv.payroll_contact                                    AS dga_pif_tv_payroll_contact,
           dga_pif_tv.payroll_phone                                      AS dga_pif_tv_payroll_phone,
           dga_pif_tv.credit_line                                        AS dga_pif_tv_credit_line,
           dga_pif_tv.credit_line_bank                                   AS dga_pif_tv_credit_line_bank,
           dga_pif_tv.credit_line_contact                                AS dga_pif_tv_credit_line_contact,
           dga_pif_tv.credit_line_phone                                  AS dga_pif_tv_credit_line_phone,
           dga_pif_tv.foreign_distribuitors                              AS dga_pif_tv_foreign_distribuitors,
           dga_pif_tv.domestic_distribuitors                             AS dga_pif_tv_domestic_distribuitors,
           dga_pif_tv.signature                                          AS dga_pif_tv_signature,
           dga_pif_tv.signature_title                                    AS dga_pif_tv_signature_title,
           dga_pif_tv.signature_print_name                               AS dga_pif_tv_signature_print_name,
           dga_pif_tv.signature_phone                                    AS dga_pif_tv_signature_phone,
           dga_pif_tv.signature_date                                     AS dga_pif_tv_signature_date,
           DATE_FORMAT(dga_pif_tv.created,'%m/%d/%Y %H:%i:%S')           AS dga_pif_tv_created,
           dga_pif_tv.created_by                                         AS dga_pif_tv_created_by,
           DATE_FORMAT(dga_pif_tv.updated,'%m/%d/%Y %H:%i:%S')           AS dga_pif_tv_updated,
           dga_pif_tv.updated_by                                         AS dga_pif_tv_updated_by,
           dga_pif_tv.status                                             AS dga_pif_tv_status
      FROM dga_pif_tv AS dga_pif_tv INNER JOIN company    AS company    ON company.id    = dga_pif_tv.company_id
                                    INNER JOIN production AS production ON production.id = dga_pif_tv.production_id;