CREATE OR REPLACE VIEW dga_upm_deal_memo_get_list(
    dga_upm_deal_memo_id,
    dga_upm_deal_memo_contact_id,
    dga_upm_deal_memo_contact_first_name,
    dga_upm_deal_memo_contact_middle_name,
    dga_upm_deal_memo_contact_last_name,
    dga_upm_deal_memo_contact_full_name,
    dga_upm_deal_memo_contact_suffix,
    dga_upm_deal_memo_contact_address,
    dga_upm_deal_memo_contact_city,
    dga_upm_deal_memo_contact_state_code,
    dga_upm_deal_memo_contact_state_name,
    dga_upm_deal_memo_contact_phone,
    dga_upm_deal_memo_contact_email,
    dga_upm_deal_memo_contact_website,
    dga_upm_deal_memo_contact_picture_path,
    dga_upm_deal_memo_ssn,
    dga_upm_deal_memo_loanout,
    dga_upm_deal_memo_fid,
    dga_upm_deal_memo_category_unit_production_manager,
    dga_upm_deal_memo_category_additional_second_assistant_director,
    dga_upm_deal_memo_category_first_assistant_director,
    dga_upm_deal_memo_category_associate_director,
    dga_upm_deal_memo_category_key_second_assistant_director,
    dga_upm_deal_memo_category_associate_director_line_cut,
    dga_upm_deal_memo_category_second_assistant_director,
    dga_upm_deal_memo_salary_studio,
    dga_upm_deal_memo_salary_studio_period_id,
    dga_upm_deal_memo_salary_location,
    dga_upm_deal_memo_salary_location_period_id,
    dga_upm_deal_memo_start_date,
    dga_upm_deal_memo_guaranteed_period_1,
    dga_upm_deal_memo_guaranteed_period_3,
    dga_upm_deal_memo_guaranteed_period_7,
    dga_upm_deal_memo_production_id,
    dga_upm_deal_memo_production_title,
    dga_upm_deal_memo_episode_id,
    dga_upm_deal_memo_episode_title,
    dga_upm_deal_memo_type_production_feature,
    dga_upm_deal_memo_type_production_multi_camera_prime_time,
    dga_upm_deal_memo_type_production_single_camera,
    dga_upm_deal_memo_type_production_other_television,
    dga_upm_deal_memo_project_info_30_lower,
    dga_upm_deal_memo_project_info_30_between,
    dga_upm_deal_memo_project_info_30_higher,
    dga_upm_deal_memo_project_info_60_lower,
    dga_upm_deal_memo_project_info_60_between,
    dga_upm_deal_memo_project_info_60_higher,
    dga_upm_deal_memo_project_info_120_lower,
    dga_upm_deal_memo_project_info_120_between,
    dga_upm_deal_memo_project_info_120_higher,
    dga_upm_deal_memo_location_studio,
    dga_upm_deal_memo_location_distant,
    dga_upm_deal_memo_location_distant_specific,
    dga_upm_deal_memo_location_both,
    dga_upm_deal_memo_location_both_specific,
    dga_upm_deal_memo_other_conditions,
    dga_upm_deal_memo_employer_name,
    dga_upm_deal_memo_employee_name,
    dga_upm_deal_memo_employee_date,
    dga_upm_deal_memo_signatory,
    dga_upm_deal_memo_signatory_by,
    dga_upm_deal_memo_signatory_date,
    dga_upm_deal_memo_created,
    dga_upm_deal_memo_created_by,
    dga_upm_deal_memo_updated,
    dga_upm_deal_memo_updated_by,
    dga_upm_deal_memo_status
) AS
    SELECT dga_upm_deal_memo.id                                                                    AS dga_upm_deal_memo_id,
           dga_upm_deal_memo.contact_id                                                            AS dga_upm_deal_memo_contact_id,
           contact.first_name                                                                      AS dga_upm_deal_memo_contact_first_name,
           contact.middle_name                                                                     AS dga_upm_deal_memo_contact_middle_name,
           contact.last_name                                                                       AS dga_upm_deal_memo_contact_last_name,
           contact_get_full_name(dga_upm_deal_memo.contact_id)                                     AS dga_upm_deal_memo_contact_full_name,
           contact.suffix                                                                          AS dga_upm_deal_memo_contact_suffix,
           contact.address                                                                         AS dga_upm_deal_memo_contact_address,
           contact.city                                                                            AS dga_upm_deal_memo_contact_city,
           contact.state_code                                                                      AS dga_upm_deal_memo_contact_state_code,
           state.name                                                                              AS dga_upm_deal_memo_contact_state_name,
           contact.phone                                                                           AS dga_upm_deal_memo_contact_phone,
           contact.email                                                                           AS dga_upm_deal_memo_contact_email,
           contact.website                                                                         AS dga_upm_deal_memo_contact_website,
           contact.picture_path                                                                    AS dga_upm_deal_memo_contact_picture_path,
           dga_upm_deal_memo.ssn                                                                   AS dga_upm_deal_memo_ssn,
           dga_upm_deal_memo.loanout                                                               AS dga_upm_deal_memo_loanout,
           dga_upm_deal_memo.fid                                                                   AS dga_upm_deal_memo_fid,
           dga_upm_deal_memo.category_unit_production_manager                                      AS dga_upm_deal_memo_category_unit_production_manager,
           dga_upm_deal_memo.category_additional_second_assistant_director                         AS dga_upm_deal_memo_category_additional_second_assistant_director,
           dga_upm_deal_memo.category_first_assistant_director                                     AS dga_upm_deal_memo_category_first_assistant_director,
           dga_upm_deal_memo.category_associate_director                                           AS dga_upm_deal_memo_category_associate_director,
           dga_upm_deal_memo.category_key_second_assistant_director                                AS dga_upm_deal_memo_category_key_second_assistant_director,
           dga_upm_deal_memo.category_associate_director_line_cut                                  AS dga_upm_deal_memo_category_associate_director_line_cut,
           dga_upm_deal_memo.category_second_assistant_director                                    AS dga_upm_deal_memo_category_second_assistant_director,
           dga_upm_deal_memo.salary_studio                                                         AS dga_upm_deal_memo_salary_studio,
           dga_upm_deal_memo.salary_studio_period_id                                               AS dga_upm_deal_memo_salary_studio_period_id,
           dga_upm_deal_memo.salary_location                                                       AS dga_upm_deal_memo_salary_location,
           dga_upm_deal_memo.salary_location_period_id                                             AS dga_upm_deal_memo_salary_location_period_id,
           dga_upm_deal_memo.start_date                                                            AS dga_upm_deal_memo_start_date,
           dga_upm_deal_memo.guaranteed_period_1                                                   AS dga_upm_deal_memo_guaranteed_period_1,
           dga_upm_deal_memo.guaranteed_period_3                                                   AS dga_upm_deal_memo_guaranteed_period_3,
           dga_upm_deal_memo.guaranteed_period_7                                                   AS dga_upm_deal_memo_guaranteed_period_7,
           dga_upm_deal_memo.production_id                                                         AS dga_upm_deal_memo_production_id,
           production.title                                                                        AS dga_upm_deal_memo_production_title,
           dga_upm_deal_memo.episode_id                                                            AS dga_upm_deal_memo_episode_id,
           episode.title                                                                           AS dga_upm_deal_memo_episode_title,
           dga_upm_deal_memo.type_production_feature                                               AS dga_upm_deal_memo_type_production_feature,
           dga_upm_deal_memo.type_production_multi_camera_prime_time                               AS dga_upm_deal_memo_type_production_multi_camera_prime_time,
           dga_upm_deal_memo.type_production_single_camera                                         AS dga_upm_deal_memo_type_production_single_camera,
           dga_upm_deal_memo.type_production_other_television                                      AS dga_upm_deal_memo_type_production_other_television,
           dga_upm_deal_memo.project_info_30_lower                                                 AS dga_upm_deal_memo_project_info_30_lower,
           dga_upm_deal_memo.project_info_30_between                                               AS dga_upm_deal_memo_project_info_30_between,
           dga_upm_deal_memo.project_info_30_higher                                                AS dga_upm_deal_memo_project_info_30_higher,
           dga_upm_deal_memo.project_info_60_lower                                                 AS dga_upm_deal_memo_project_info_60_lower,
           dga_upm_deal_memo.project_info_60_between                                               AS dga_upm_deal_memo_project_info_60_between,
           dga_upm_deal_memo.project_info_60_higher                                                AS dga_upm_deal_memo_project_info_60_higher,
           dga_upm_deal_memo.project_info_120_lower                                                AS dga_upm_deal_memo_project_info_120_lower,
           dga_upm_deal_memo.project_info_120_between                                              AS dga_upm_deal_memo_project_info_120_between,
           dga_upm_deal_memo.project_info_120_higher                                               AS dga_upm_deal_memo_project_info_120_higher,
           dga_upm_deal_memo.location_studio                                                       AS dga_upm_deal_memo_location_studio,
           dga_upm_deal_memo.location_distant                                                      AS dga_upm_deal_memo_location_distant,
           dga_upm_deal_memo.location_distant_specific                                             AS dga_upm_deal_memo_location_distant_specific,
           dga_upm_deal_memo.location_both                                                         AS dga_upm_deal_memo_location_both,
           dga_upm_deal_memo.location_both_specific                                                AS dga_upm_deal_memo_location_both_specific,
           dga_upm_deal_memo.other_conditions                                                      AS dga_upm_deal_memo_other_conditions,
           dga_upm_deal_memo.employer_name                                                         AS dga_upm_deal_memo_employer_name,
           dga_upm_deal_memo.employee_name                                                         AS dga_upm_deal_memo_employee_name,
           dga_upm_deal_memo.employee_date                                                         AS dga_upm_deal_memo_employee_date,
           dga_upm_deal_memo.signatory                                                             AS dga_upm_deal_memo_signatory,
           dga_upm_deal_memo.signatory_by                                                          AS dga_upm_deal_memo_signatory_by,
           dga_upm_deal_memo.signatory_date                                                        AS dga_upm_deal_memo_signatory_date,
           DATE_FORMAT(dga_upm_deal_memo.created,'%m/%d/%Y %H:%i:%S')                              AS dga_upm_deal_memo_created,
           dga_upm_deal_memo.created_by                                                            AS dga_upm_deal_memo_created_by,
           DATE_FORMAT(dga_upm_deal_memo.updated,'%m/%d/%Y %H:%i:%S')                              AS dga_upm_deal_memo_updated,
           dga_upm_deal_memo.updated_by                                                            AS dga_upm_deal_memo_updated_by,
           dga_upm_deal_memo.status                                                                AS dga_upm_deal_memo_status
      FROM dga_upm_deal_memo AS dga_upm_deal_memo INNER JOIN contact    AS contact    ON contact.id    = dga_upm_deal_memo.contact_id
                                                  INNER JOIN state      AS state      ON state.code    = contact.state_code
                                                  INNER JOIN production AS production ON production.id = dga_upm_deal_memo.production_id
                                                  INNER JOIN episode    AS episode    ON episode.id    = dga_upm_deal_memo.episode_id;