CREATE OR REPLACE VIEW location_get_list(
    location_id,
    location_name,
    location_location_type_id,
    location_location_type_name,
    location_address,
    location_city,
    location_state_code,
    location_state_name,
    location_zipcode,
    location_phone,
    location_latitude,
    location_longitude,
    location_contact_city,
    location_contact_state_code,
    location_contact_state_name,
    location_contact_zipcode,
    location_contact_phone,
    location_contact_email,
    location_contact_website,
    location_created,
    location_created_by,
    location_updated,
    location_updated_by,
    location_status
) AS
    SELECT location.id                                       AS location_id,
           location.name                                     AS location_name,
           location.location_type_id                         AS location_location_type_id,
           location_type.name                                AS location_location_type_name,
           location.address                                  AS location_address,
           location.city                                     AS location_city,
           location.state_code                               AS location_state_code,
           state.name                                        AS location_state_name,
           location.zipcode                                  AS location_zipcode,
           location.phone                                    AS location_phone,
           location.latitude                                 AS location_latitude,
           location.longitude                                AS location_longitude,
           location.contact_city                             AS location_contact_city,
           location.contact_state_code                       AS location_contact_state_code,
           contact_state.name                                AS location_contact_state_name,
           location.contact_zipcode                          AS location_contact_zipcode,
           location.contact_phone                            AS location_contact_phone,
           location.contact_email                            AS location_contact_email,
           location.contact_website                          AS location_contact_website,
           DATE_FORMAT(location.created,'%m/%d/%Y %H:%i:%S') AS location_created,
           location.created_by                               AS location_created_by,
           DATE_FORMAT(location.updated,'%m/%d/%Y %H:%i:%S') AS location_updated,
           location.updated_by                               AS location_updated_by,
           location.status                                   AS location_status
      FROM location AS location INNER JOIN location_type AS location_type ON location_type.id   = location.location_type_id
                                LEFT  JOIN state         AS state         ON state.code         = location.state_code
                                LEFT  JOIN state         AS contact_state ON contact_state.code = location.contact_state_code;