CREATE OR REPLACE VIEW sav_final_cast_list_info_item_get_list(
    sav_final_cast_list_info_item_id,
    sav_final_cast_list_info_item_sav_final_cast_list_info_id,
    sav_final_cast_list_info_item_production_id,
    sav_final_cast_list_info_item_production_title,
    sav_final_cast_list_info_item_contact_id,
    sav_final_cast_list_info_item_contact_full_name,
    sav_final_cast_list_info_item_contact_address,
    sav_final_cast_list_info_item_contact_city,
    sav_final_cast_list_info_item_contact_state_code,
    sav_final_cast_list_info_item_contact_phone,
    sav_final_cast_list_info_item_contact_email,
    sav_final_cast_list_info_item_contact_ssn,
    sav_final_cast_list_info_item_contact_name_ssn,
    sav_final_cast_list_info_item_loan_out_corp,
    sav_final_cast_list_info_item_federal_id,
    sav_final_cast_list_info_item_loan_out_corp_federal_id,
    sav_final_cast_list_info_item_days_number,
    sav_final_cast_list_info_item_weeks_number,
    sav_final_cast_list_info_item_start_date,
    sav_final_cast_list_info_item_end_date,
    sav_final_cast_list_info_item_contract_type,
    sav_final_cast_list_info_item_sav_performer_type_id,
    sav_final_cast_list_info_item_sav_performer_type_code,
    sav_final_cast_list_info_item_sav_performer_type_title,
    sav_final_cast_list_info_item_sav_performer_type_full_title,
    sav_final_cast_list_info_item_salary_total_gross,
    sav_final_cast_list_info_item_salary_base,
    sav_final_cast_list_info_item_units_type,
    sav_final_cast_list_info_item_units_salary,
    sav_final_cast_list_info_item_units_total,
    sav_final_cast_list_info_item_created,
    sav_final_cast_list_info_item_created_by,
    sav_final_cast_list_info_item_updated,
    sav_final_cast_list_info_item_updated_by,
    sav_final_cast_list_info_item_status
) AS
    SELECT sav_final_cast_list_info_item.id                                                                               AS sav_final_cast_list_info_item_id,
           sav_final_cast_list_info_item.sav_final_cast_list_info_id                                                      AS sav_final_cast_list_info_item_sav_final_cast_list_info_id,
           sav_final_cast_list_info_item.production_id                                                                    AS sav_final_cast_list_info_item_production_id,
           production.title                                                                                               AS sav_final_cast_list_info_item_production_title,
           sav_final_cast_list_info_item.contact_id                                                                       AS sav_final_cast_list_info_item_contact_id,
           contact_get_full_name(contact.id)                                                                              AS sav_final_cast_list_info_item_contact_full_name,
           contact.address                                                                                                AS sav_final_cast_list_info_item_contact_address,
           contact.city                                                                                                   AS sav_final_cast_list_info_item_contact_city,
           contact.state_code                                                                                             AS sav_final_cast_list_info_item_contact_state_code,
           contact.phone                                                                                                  AS sav_final_cast_list_info_item_contact_phone,
           contact.email                                                                                                  AS sav_final_cast_list_info_item_contact_email,
           contact.ssn                                                                                                    AS sav_final_cast_list_info_item_contact_ssn,
           CONCAT(contact_get_full_name(contact.id), ' SSN# ', contact.ssn)                                               AS sav_final_cast_list_info_item_contact_name_ssn,
           sav_final_cast_list_info_item.loan_out_corp                                                                    AS sav_final_cast_list_info_item_loan_out_corp,
           sav_final_cast_list_info_item.federal_id                                                                       AS sav_final_cast_list_info_item_federal_id,
           CONCAT(sav_final_cast_list_info_item.loan_out_corp, ' Federal ID# ', sav_final_cast_list_info_item.federal_id) AS sav_final_cast_list_info_item_loan_out_corp_federal_id,
           sav_final_cast_list_info_item.days_number                                                                      AS sav_final_cast_list_info_item_days_number,
           sav_final_cast_list_info_item.weeks_number                                                                     AS sav_final_cast_list_info_item_weeks_number,
           DATE_FORMAT(sav_final_cast_list_info_item.start_date,'%m/%d/%Y')                                               AS sav_final_cast_list_info_item_start_date,
           DATE_FORMAT(sav_final_cast_list_info_item.end_date,'%m/%d/%Y')                                                 AS sav_final_cast_list_info_item_end_date,
           sav_final_cast_list_info_item.contract_type                                                                    AS sav_final_cast_list_info_item_contract_type,
           sav_final_cast_list_info_item.sav_performer_type_id                                                            AS sav_final_cast_list_info_item_sav_performer_type_id,
           sav_performer_type.code                                                                                        AS sav_final_cast_list_info_item_sav_performer_type_code,
           sav_performer_type.title                                                                                       AS sav_final_cast_list_info_item_sav_performer_type_title,
           CONCAT(TRIM(sav_performer_type.code),' - ',TRIM(sav_performer_type.title))                                     AS sav_final_cast_list_info_item_sav_performer_type_full_title,
           sav_final_cast_list_info_item.salary_total_gross                                                               AS sav_final_cast_list_info_item_salary_total_gross,
           sav_final_cast_list_info_item.salary_base                                                                      AS sav_final_cast_list_info_item_salary_base,
           sav_final_cast_list_info_item.units_type                                                                       AS sav_final_cast_list_info_item_units_type,
           sav_final_cast_list_info_item.units_salary                                                                     AS sav_final_cast_list_info_item_units_salary,
           sav_final_cast_list_info_item.units_total                                                                      AS sav_final_cast_list_info_item_units_total,
           DATE_FORMAT(sav_final_cast_list_info_item.created,'%m/%d/%Y %H:%i:%S')                                         AS sav_final_cast_list_info_item_created,
           sav_final_cast_list_info_item.created_by                                                                       AS sav_final_cast_list_info_item_created_by,
           DATE_FORMAT(sav_final_cast_list_info_item.updated,'%m/%d/%Y %H:%i:%S')                                         AS sav_final_cast_list_info_item_updated,
           sav_final_cast_list_info_item.updated_by                                                                       AS sav_final_cast_list_info_item_updated_by,
           sav_final_cast_list_info_item.status                                                                           AS sav_final_cast_list_info_item_status
      FROM sav_final_cast_list_info_item AS sav_final_cast_list_info_item INNER JOIN production         AS production         ON production.id         = sav_final_cast_list_info_item.production_id
                                                                          INNER JOIN contact            AS contact            ON contact.id            = sav_final_cast_list_info_item.contact_id
                                                                          INNER JOIN sav_performer_type AS sav_performer_type ON sav_performer_type.id = sav_final_cast_list_info_item.sav_performer_type_id;