CREATE OR REPLACE VIEW transaction_get_list(
    transaction_id,
    transaction_media_company_id,
    transaction_business_group_id,
    transaction_network_id,
    transaction_production_id,
    transaction_season_id,
    transaction_episode_id,
    transaction_ledger_id,
    transaction_account_id,
    transaction_subaccount_id,
    transaction_description,
    transaction_budget,
    transaction_total_budget,
    transaction_guarantee,
    transaction_period_id,
    transaction_period_name,
    transaction_period_period,
    transaction_period_plural,
    transaction_actual,
    transaction_total_actual,
    transaction_comment,
    transaction_created,
    transaction_created_by,
    transaction_updated,
    transaction_updated_by,
    transaction_status
) AS
    SELECT transaction.id                                       AS transaction_id,
           transaction.media_company_id                         AS transaction_media_company_id,
           transaction.business_group_id                        AS transaction_business_group_id,
           transaction.network_id                               AS transaction_network_id,
           transaction.production_id                            AS transaction_production_id,
           transaction.season_id                                AS transaction_season_id,
           transaction.episode_id                               AS transaction_episode_id,
           transaction.ledger_id                                AS transaction_ledger_id,
           transaction.account_id                               AS transaction_account_id,
           transaction.subaccount_id                            AS transaction_subaccount_id,
           transaction.description                              AS transaction_description,
           transaction.budget                                   AS transaction_budget,
           transaction.total_budget                             AS transaction_total_budget,
           transaction.guarantee                                AS transaction_guarantee,
           transaction.period_id                                AS transaction_period_id,
           period.name                                          AS transaction_period_name,
           period.period                                        AS transaction_period_period,
           period.plural                                        AS transaction_period_plural,
           transaction.actual                                   AS transaction_actual,
           transaction.total_actual                             AS transaction_total_actual,
           transaction.comment                                  AS transaction_comment,
           DATE_FORMAT(transaction.created,'%m/%d/%Y %H:%i:%S') AS transaction_created,
           transaction.created_by                               AS transaction_created_by,
           DATE_FORMAT(transaction.updated,'%m/%d/%Y %H:%i:%S') AS transaction_updated,
           transaction.updated_by                               AS transaction_updated_by,
           transaction.status                                   AS transaction_status
      FROM transaction AS transaction INNER JOIN period ON period.id = transaction.period_id;