CREATE OR REPLACE VIEW user_get_list(
    user_name,
    user_email,
    user_first_name,
    user_middle_name,
    user_last_name,
    user_suffix,
    user_address,
    user_city,
    user_state_code,
    user_phone,
    user_website,
    user_picture_path,
    user_created,
    user_created_by,
    user_updated,
    user_updated_by,
    user_status
) AS
    SELECT user.user_name                                     AS user_name,
           user.email                                         AS user_email,
           user.first_name                                    AS user_first_name,
           user.middle_name                                   AS user_middle_name,
           user.last_name                                     AS user_last_name,
           user.suffix                                        AS user_suffix,
           user.address                                       AS user_address,
           user.city                                          AS user_city,
           user.state_code                                    AS user_state_code,
           user.phone                                         AS user_phone,
           user.website                                       AS user_website,
           user.picture_path                                  AS user_picture_path,
           DATE_FORMAT(user.created,'%m/%d/%Y %H:%i:%S')      AS user_created,
           user.created_by                                    AS user_created_by,
           DATE_FORMAT(user.updated,'%m/%d/%Y %H:%i:%S')      AS user_updated,
           user.updated_by                                    AS user_updated_by,
           user.status                                        AS user_status
      FROM user AS user;