DELIMITER //
CREATE PROCEDURE dga_stage_manager_deal_memo_set_list(
    IN  dga_stage_manager_deal_memo_id                                  INT,
    IN  dga_stage_manager_deal_memo_contact_id                          INT,
    IN  dga_stage_manager_deal_memo_ssn                                 VARCHAR(11),
    IN  dga_stage_manager_deal_memo_loanout                             VARCHAR(30),
    IN  dga_stage_manager_deal_memo_fid                                 VARCHAR(30),
    IN  dga_stage_manager_deal_memo_salary                              DECIMAL,
    IN  dga_stage_manager_deal_memo_salary_period_id                    INT,
    IN  dga_stage_manager_deal_memo_aditional_time                      DECIMAL,
    IN  dga_stage_manager_deal_memo_aditional_time_period_id            INT,
    IN  dga_stage_manager_deal_memo_start_date                          DATE,
    IN  dga_stage_manager_deal_memo_guaranteed                          INT,
    IN  dga_stage_manager_deal_memo_guaranteed_period_id                INT,
    IN  dga_stage_manager_deal_memo_production_id                       INT,
    IN  dga_stage_manager_deal_memo_episode_id                          INT,
    IN  dga_stage_manager_deal_memo_category_associate_director         CHAR(1),
    IN  dga_stage_manager_deal_memo_category_stage_manager              CHAR(1),
    IN  dga_stage_manager_deal_memo_category_aditional_stage_manager    CHAR(1),
    IN  dga_stage_manager_deal_memo_prime_time_per_week_studio          CHAR(1),
    IN  dga_stage_manager_deal_memo_prime_time_per_week_location        CHAR(1),
    IN  dga_stage_manager_deal_memo_prime_time_per_day_studio           CHAR(1),
    IN  dga_stage_manager_deal_memo_prime_time_per_day_location         CHAR(1),
    IN  dga_stage_manager_deal_memo_other_per_week_40                   CHAR(1),
    IN  dga_stage_manager_deal_memo_other_per_week_flat_60              CHAR(1),
    IN  dga_stage_manager_deal_memo_other_per_day_8                     CHAR(1),
    IN  dga_stage_manager_deal_memo_other_per_day_flat_12               CHAR(1),
    IN  dga_stage_manager_deal_memo_project_info_30_lower               CHAR(1),
    IN  dga_stage_manager_deal_memo_project_info_30_between             CHAR(1),
    IN  dga_stage_manager_deal_memo_project_info_30_higher              CHAR(1),
    IN  dga_stage_manager_deal_memo_project_info_60_lower               CHAR(1),
    IN  dga_stage_manager_deal_memo_project_info_60_between             CHAR(1),
    IN  dga_stage_manager_deal_memo_project_info_60_higher              CHAR(1),
    IN  dga_stage_manager_deal_memo_project_info_120_lower              CHAR(1),
    IN  dga_stage_manager_deal_memo_project_info_120_between            CHAR(1),
    IN  dga_stage_manager_deal_memo_project_info_120_higher             CHAR(1),
    IN  dga_stage_manager_deal_memo_other_conditions                    VARCHAR(255),
    -- IN  dga_stage_manager_deal_memo_employer_name                       VARCHAR(50),
    IN  dga_stage_manager_deal_memo_employee_name                       VARCHAR(50),
    IN  dga_stage_manager_deal_memo_employee_date                       DATE,
    IN  dga_stage_manager_deal_memo_signatory                           VARCHAR(50),
    IN  dga_stage_manager_deal_memo_signatory_by                        VARCHAR(50),
    IN  dga_stage_manager_deal_memo_signatory_date                      DATE,
    IN  dga_stage_manager_deal_memo_created_by                          VARCHAR(30),
    IN  dga_stage_manager_deal_memo_updated_by                          VARCHAR(30),
    IN  dga_stage_manager_deal_memo_status                              VARCHAR(30),
    OUT return_value                                                   INTEGER
)
BEGIN
    DECLARE ROW_EXISTS INTEGER;

    SELECT COUNT(*)
      INTO ROW_EXISTS
      FROM dga_stage_manager_deal_memo
     WHERE id = dga_stage_manager_deal_memo_id;

     IF (ROW_EXISTS = 0) THEN
        INSERT INTO dga_stage_manager_deal_memo
        (
            contact_id,
            ssn,
            loanout,
            fid,
            salary,
            salary_period_id,
            aditional_time,
            aditional_time_period_id,
            start_date,
            guaranteed,
            guaranteed_period_id,
            production_id,
            episode_id,
            category_associate_director,
            category_stage_manager,
            category_aditional_stage_manager,
            prime_time_per_week_studio,
            prime_time_per_week_location,
            prime_time_per_day_studio,
            prime_time_per_day_location,
            other_per_week_40,
            other_per_week_flat_60,
            other_per_day_8,
            other_per_day_flat_12,
            project_info_30_lower,
            project_info_30_between,
            project_info_30_higher,
            project_info_60_lower,
            project_info_60_between,
            project_info_60_higher,
            project_info_120_lower,
            project_info_120_between,
            project_info_120_higher,
            other_conditions,
            -- employer_name,
            employee_name,
            employee_date,
            signatory,
            signatory_by,
            signatory_date,
            created_by,
            updated_by,
            status
        )
        VALUES
        (
            dga_stage_manager_deal_memo_contact_id,
            dga_stage_manager_deal_memo_ssn,
            dga_stage_manager_deal_memo_loanout,
            dga_stage_manager_deal_memo_fid,
            dga_stage_manager_deal_memo_salary,
            dga_stage_manager_deal_memo_salary_period_id,
            dga_stage_manager_deal_memo_aditional_time,
            dga_stage_manager_deal_memo_aditional_time_period_id,
            dga_stage_manager_deal_memo_start_date,
            dga_stage_manager_deal_memo_guaranteed,
            dga_stage_manager_deal_memo_guaranteed_period_id,
            dga_stage_manager_deal_memo_production_id,
            dga_stage_manager_deal_memo_episode_id,
            dga_stage_manager_deal_memo_category_associate_director,
            dga_stage_manager_deal_memo_category_stage_manager,
            dga_stage_manager_deal_memo_category_aditional_stage_manager,
            dga_stage_manager_deal_memo_prime_time_per_week_studio,
            dga_stage_manager_deal_memo_prime_time_per_week_location,
            dga_stage_manager_deal_memo_prime_time_per_day_studio,
            dga_stage_manager_deal_memo_prime_time_per_day_location,
            dga_stage_manager_deal_memo_other_per_week_40,
            dga_stage_manager_deal_memo_other_per_week_flat_60,
            dga_stage_manager_deal_memo_other_per_day_8,
            dga_stage_manager_deal_memo_other_per_day_flat_12,
            dga_stage_manager_deal_memo_project_info_30_lower,
            dga_stage_manager_deal_memo_project_info_30_between,
            dga_stage_manager_deal_memo_project_info_30_higher,
            dga_stage_manager_deal_memo_project_info_60_lower,
            dga_stage_manager_deal_memo_project_info_60_between,
            dga_stage_manager_deal_memo_project_info_60_higher,
            dga_stage_manager_deal_memo_project_info_120_lower,
            dga_stage_manager_deal_memo_project_info_120_between,
            dga_stage_manager_deal_memo_project_info_120_higher,
            dga_stage_manager_deal_memo_other_conditions,
            -- dga_stage_manager_deal_memo_employer_name,
            dga_stage_manager_deal_memo_employee_name,
            dga_stage_manager_deal_memo_employee_date,
            dga_stage_manager_deal_memo_signatory,
            dga_stage_manager_deal_memo_signatory_by,
            dga_stage_manager_deal_memo_signatory_date,
            dga_stage_manager_deal_memo_created_by,
            dga_stage_manager_deal_memo_updated_by,
            'CREATED'
        );

        SET return_value = LAST_INSERT_ID();
     END IF;

     IF (ROW_EXISTS >= 1) THEN
        UPDATE dga_stage_manager_deal_memo
           SET id                               = dga_stage_manager_deal_memo_id,
               contact_id                       = dga_stage_manager_deal_memo_contact_id,
               ssn                              = dga_stage_manager_deal_memo_ssn,
               loanout                          = dga_stage_manager_deal_memo_loanout,
               fid                              = dga_stage_manager_deal_memo_fid,
               salary                           = dga_stage_manager_deal_memo_salary,
               salary_period_id                 = dga_stage_manager_deal_memo_salary_period_id,
               aditional_time                   = dga_stage_manager_deal_memo_aditional_time,
               aditional_time_period_id         = dga_stage_manager_deal_memo_aditional_time_period_id,
               start_date                       = dga_stage_manager_deal_memo_start_date,
               guaranteed                       = dga_stage_manager_deal_memo_guaranteed,
               guaranteed_period_id             = dga_stage_manager_deal_memo_guaranteed_period_id,
               production_id                    = dga_stage_manager_deal_memo_production_id,
               episode_id                       = dga_stage_manager_deal_memo_episode_id,
               category_associate_director      = dga_stage_manager_deal_memo_category_associate_director,
               category_stage_manager           = dga_stage_manager_deal_memo_category_stage_manager,
               category_aditional_stage_manager = dga_stage_manager_deal_memo_category_aditional_stage_manager,
               prime_time_per_week_studio       = dga_stage_manager_deal_memo_prime_time_per_week_studio,
               prime_time_per_week_location     = dga_stage_manager_deal_memo_prime_time_per_week_location,
               prime_time_per_day_studio        = dga_stage_manager_deal_memo_prime_time_per_day_studio,
               prime_time_per_day_location      = dga_stage_manager_deal_memo_prime_time_per_day_location,
               other_per_week_40                = dga_stage_manager_deal_memo_other_per_week_40,
               other_per_week_flat_60           = dga_stage_manager_deal_memo_other_per_week_flat_60,
               other_per_day_8                  = dga_stage_manager_deal_memo_other_per_day_8,
               other_per_day_flat_12            = dga_stage_manager_deal_memo_other_per_day_flat_12,
               project_info_30_lower            = dga_stage_manager_deal_memo_project_info_30_lower,
               project_info_30_between          = dga_stage_manager_deal_memo_project_info_30_between,
               project_info_30_higher           = dga_stage_manager_deal_memo_project_info_30_higher,
               project_info_60_lower            = dga_stage_manager_deal_memo_project_info_60_lower,
               project_info_60_between          = dga_stage_manager_deal_memo_project_info_60_between,
               project_info_60_higher           = dga_stage_manager_deal_memo_project_info_60_higher,
               project_info_120_lower           = dga_stage_manager_deal_memo_project_info_120_lower,
               project_info_120_between         = dga_stage_manager_deal_memo_project_info_120_between,
               project_info_120_higher          = dga_stage_manager_deal_memo_project_info_120_higher,
               other_conditions                 = dga_stage_manager_deal_memo_other_conditions,
            --    employer_name                    = dga_stage_manager_deal_memo_employer_name,
               employee_name                    = dga_stage_manager_deal_memo_employee_name,
               employee_date                    = dga_stage_manager_deal_memo_employee_date,
               signatory                        = dga_stage_manager_deal_memo_signatory,
               signatory_by                     = dga_stage_manager_deal_memo_signatory_by,
               signatory_date                   = dga_stage_manager_deal_memo_signatory_date,
               created_by                       = dga_stage_manager_deal_memo_created_by,
               updated_by                       = dga_stage_manager_deal_memo_updated_by,
               status = 'UPDATED'
         WHERE id                 =    dga_stage_manager_deal_memo_id;

         SET return_value = dga_stage_manager_deal_memo_id;
     END IF;

     COMMIT;
END //
DELIMITER ;