DELIMITER //
CREATE PROCEDURE dga_pif_tv_set_list(
    IN dga_pif_tv_id                                             INT,
    IN dga_pif_tv_company_id                                     INT,
    IN dga_pif_tv_contact_id                                     INT,
    IN dga_pif_tv_production_id                                  INT,
    IN dga_pif_tv_copyright_holder                               VARCHAR(50),
    IN dga_pif_tv_copyright_holder_name                          VARCHAR(50),
    IN dga_pif_tv_copyright_holder_phone                         VARCHAR(20),
    IN dga_pif_tv_writers                                        VARCHAR(255),
    IN dga_pif_tv_budget                                         DECIMAL,
    IN dga_pif_tv_locations                                      VARCHAR(255),
    IN dga_pif_tv_date_pre_production                            DATE,
    IN dga_pif_tv_date_principal_photography                     DATE,
    IN dga_pif_tv_date_wrap                                      DATE,
    IN dga_pif_tv_format_multi_camera                            CHAR(1),
    IN dga_pif_tv_format_single_camera                           CHAR(1),
    IN dga_pif_tv_produced_digital                               CHAR(1),
    IN dga_pif_tv_produced_film                                  CHAR(1),
    IN dga_pif_tv_produced_tape                                  CHAR(1),
    IN dga_pif_tv_produced_live                                  CHAR(1),
    IN dga_pif_tv_produced_other                                 CHAR(1),
    IN dga_pif_tv_produced_other_description                     VARCHAR(50),
    IN dga_pif_tv_program_type_dramatic                          CHAR(1),
    IN dga_pif_tv_program_type_sitcom                            CHAR(1),
    IN dga_pif_tv_program_type_reality                           CHAR(1),
    IN dga_pif_tv_program_type_variety                           CHAR(1),
    IN dga_pif_tv_program_type_other                             CHAR(1),
    IN dga_pif_tv_program_type_other_description                 VARCHAR(50),
    IN dga_pif_tv_program_length_30                              CHAR(1),
    IN dga_pif_tv_program_length_60                              CHAR(1),
    IN dga_pif_tv_program_length_90                              CHAR(1),
    IN dga_pif_tv_program_length_120                             CHAR(1),
    IN dga_pif_tv_program_length_other                           CHAR(1),
    IN dga_pif_tv_program_length_other_description               VARCHAR(50),
    IN dga_pif_tv_network                                        CHAR(1),
    IN dga_pif_tv_network_abc                                    CHAR(1),
    IN dga_pif_tv_network_cbs                                    CHAR(1),
    IN dga_pif_tv_network_fox                                    CHAR(1),
    IN dga_pif_tv_network_nbc                                    CHAR(1),
    IN dga_pif_tv_network_pbs                                    CHAR(1),
    IN dga_pif_tv_network_upn                                    CHAR(1),
    IN dga_pif_tv_network_wb                                     CHAR(1),
    IN dga_pif_tv_network_syndication                            CHAR(1),
    IN dga_pif_tv_network_syndication_description                VARCHAR(50),
    IN dga_pif_tv_basic_cable                                    CHAR(1),
    IN dga_pif_tv_basic_cable_a_and_e                            CHAR(1),
    IN dga_pif_tv_basic_cable_disney                             CHAR(1),
    IN dga_pif_tv_basic_cable_lifetime                           CHAR(1),
    IN dga_pif_tv_basic_cable_mtv                                CHAR(1),
    IN dga_pif_tv_basic_cable_nickelodeon                        CHAR(1),
    IN dga_pif_tv_basic_cable_tnt                                CHAR(1),
    IN dga_pif_tv_basic_cable_usa                                CHAR(1),
    IN dga_pif_tv_basic_cable_other                              CHAR(1),
    IN dga_pif_tv_basic_cable_other_description                  VARCHAR(50),
    IN dga_pif_tv_pay_tv                                         CHAR(1),
    IN dga_pif_tv_pay_tv_hbo                                     CHAR(1),
    IN dga_pif_tv_pay_tv_showtime                                CHAR(1),
    IN dga_pif_tv_pay_tv_tmc                                     CHAR(1),
    IN dga_pif_tv_pay_tv_starz                                   CHAR(1),
    IN dga_pif_tv_pay_tv_cinemax                                 CHAR(1),
    IN dga_pif_tv_pay_tv_other                                   CHAR(1),
    IN dga_pif_tv_pay_tv_other_description                       VARCHAR(50),
    IN dga_pif_tv_pilot                                          CHAR(1),
    IN dga_pif_tv_direct_to_video                                CHAR(1),
    IN dga_pif_tv_other                                          CHAR(1),
    IN dga_pif_tv_other_description                              VARCHAR(50),
    IN dga_pif_tv_employee_info_director_name                    VARCHAR(100),
    IN dga_pif_tv_employee_info_1_name                           VARCHAR(100),
    IN dga_pif_tv_employee_info_1_upm                            CHAR(1),
    IN dga_pif_tv_employee_info_1_associate_director             CHAR(1),
    IN dga_pif_tv_employee_info_2_name                           VARCHAR(100),
    IN dga_pif_tv_employee_info_2_first_assistant_director       CHAR(1),
    IN dga_pif_tv_employee_info_2_stage_manager                  CHAR(1),
    IN dga_pif_tv_employee_info_3_name                           VARCHAR(100),
    IN dga_pif_tv_employee_info_3_key_second_assistant_director  CHAR(1),
    IN dga_pif_tv_employee_info_3_second_stage_manager           CHAR(1),
    IN dga_pif_tv_employee_info_4_name                           VARCHAR(100),
    IN dga_pif_tv_employee_info_4_second_assistant_director      CHAR(1),
    IN dga_pif_tv_employee_info_4_third_stage_manager            CHAR(1),
    IN dga_pif_tv_employee_info_5_name                           VARCHAR(100),
    IN dga_pif_tv_employee_info_5_add_second_assistant_director  CHAR(1),
    IN dga_pif_tv_employee_info_5_production_associate           CHAR(1),
    IN dga_pif_tv_employee_info_6_name                           VARCHAR(100),
    IN dga_pif_tv_employee_info_6_associate_director             CHAR(1),
    IN dga_pif_tv_employee_info_7_name                           VARCHAR(100),
    IN dga_pif_tv_employee_info_7_associate_director_line_cut    CHAR(1),
    IN dga_pif_tv_employee_info_other_description                VARCHAR(50),
    IN dga_pif_tv_affiliations_sav                               CHAR(1),
    IN dga_pif_tv_affiliations_wga                               CHAR(1),
    IN dga_pif_tv_affiliations_dcg                               CHAR(1),
    IN dga_pif_tv_affiliations_aftra                             CHAR(1),
    IN dga_pif_tv_affiliations_iatse                             CHAR(1),
    IN dga_pif_tv_affiliations_nabet                             CHAR(1),
    IN dga_pif_tv_affiliations_afm                               CHAR(1),
    IN dga_pif_tv_affiliations_actra                             CHAR(1),
    IN dga_pif_tv_affiliations_other                             CHAR(1),
    IN dga_pif_tv_affiliations_other_description                 VARCHAR(50),
    IN dga_pif_tv_employment_contact_name                        VARCHAR(100),
    IN dga_pif_tv_employment_contacr_phone                       VARCHAR(20),
    IN dga_pif_tv_residuals_contact_name                         VARCHAR(100),
    IN dga_pif_tv_residuals_contacr_phone                        VARCHAR(20),
    IN dga_pif_tv_primary_finance_source                         VARCHAR(100),
    IN dga_pif_tv_primary_finance_contact                        VARCHAR(100),
    IN dga_pif_tv_primary_finance_phone                          VARCHAR(20),
    IN dga_pif_tv_completion_bond_company                        VARCHAR(100),
    IN dga_pif_tv_completion_bond_contact                        VARCHAR(100),
    IN dga_pif_tv_completion_bond_phone                          VARCHAR(20),
    IN dga_pif_tv_payroll_company                                VARCHAR(100),
    IN dga_pif_tv_payroll_contact                                VARCHAR(100),
    IN dga_pif_tv_payroll_phone                                  VARCHAR(20),
    IN dga_pif_tv_credit_line                                    CHAR(1),
    IN dga_pif_tv_credit_line_bank                               VARCHAR(100),
    IN dga_pif_tv_credit_line_contact                            VARCHAR(100),
    IN dga_pif_tv_credit_line_phone                              VARCHAR(20),
    IN dga_pif_tv_foreign_distribuitors                          VARCHAR(255),
    IN dga_pif_tv_domestic_distribuitors                         VARCHAR(255),
    IN dga_pif_tv_signature                                      VARCHAR(100),
    IN dga_pif_tv_signature_title                                VARCHAR(100),
    IN dga_pif_tv_signature_print_name                           VARCHAR(100),
    IN dga_pif_tv_signature_phone                                VARCHAR(20),
    IN dga_pif_tv_signature_date                                 DATE,
    IN dga_pif_tv_created_by                                     VARCHAR(30),
    IN dga_pif_tv_updated_by                                     VARCHAR(30),
    IN dga_pif_tv_status                                         VARCHAR(30),
    OUT return_value                                             INTEGER
)
BEGIN
    DECLARE ROW_EXISTS INTEGER;

    SELECT COUNT(*)
      INTO ROW_EXISTS
      FROM dga_pif_tv
     WHERE id = dga_pif_tv_id;

     IF (ROW_EXISTS = 0) THEN
        INSERT INTO dga_pif_tv
        (
            company_id,
            contact_id,
            production_id,
            copyright_holder,
            copyright_holder_name,
            copyright_holder_phone,
            writers,
            budget,
            locations,
            date_pre_production,
            date_principal_photography,
            date_wrap,
            format_multi_camera,
            format_single_camera,
            produced_digital,
            produced_film,
            produced_tape,
            produced_live,
            produced_other,
            produced_other_description,
            program_type_dramatic,
            program_type_sitcom,
            program_type_reality,
            program_type_variety,
            program_type_other,
            program_type_other_description,
            program_length_30,
            program_length_60,
            program_length_90,
            program_length_120,
            program_length_other,
            program_length_other_description,
            network,
            network_abc,
            network_cbs,
            network_fox,
            network_nbc,
            network_pbs,
            network_upn,
            network_wb,
            network_syndication,
            network_syndication_description,
            basic_cable,
            basic_cable_a_and_e,
            basic_cable_disney,
            basic_cable_lifetime,
            basic_cable_mtv,
            basic_cable_nickelodeon,
            basic_cable_tnt,
            basic_cable_usa,
            basic_cable_other,
            basic_cable_other_description,
            pay_tv,
            pay_tv_hbo,
            pay_tv_showtime,
            pay_tv_tmc,
            pay_tv_starz,
            pay_tv_cinemax,
            pay_tv_other,
            pay_tv_other_description,
            pilot,
            direct_to_video,
            other,
            other_description,
            employee_info_director_name,
            employee_info_1_name,
            employee_info_1_upm,
            employee_info_1_associate_director,
            employee_info_2_name,
            employee_info_2_first_assistant_director,
            employee_info_2_stage_manager,
            employee_info_3_name,
            employee_info_3_key_second_assistant_director,
            employee_info_3_second_stage_manager,
            employee_info_4_name,
            employee_info_4_second_assistant_director,
            employee_info_4_third_stage_manager,
            employee_info_5_name,
            employee_info_5_add_second_assistant_director,
            employee_info_5_production_associate,
            employee_info_6_name,
            employee_info_6_associate_director,
            employee_info_7_name,
            employee_info_7_associate_director_line_cut,
            employee_info_other_description,
            affiliations_sav,
            affiliations_wga,
            affiliations_dcg,
            affiliations_aftra,
            affiliations_iatse,
            affiliations_nabet,
            affiliations_afm,
            affiliations_actra,
            affiliations_other,
            affiliations_other_description,
            employment_contact_name,
            employment_contacr_phone,
            residuals_contact_name,
            residuals_contacr_phone,
            primary_finance_source,
            primary_finance_contact,
            primary_finance_phone,
            completion_bond_company,
            completion_bond_contact,
            completion_bond_phone,
            payroll_company,
            payroll_contact,
            payroll_phone,
            credit_line,
            credit_line_bank,
            credit_line_contact,
            credit_line_phone,
            foreign_distribuitors,
            domestic_distribuitors,
            signature,
            signature_title,
            signature_print_name,
            signature_phone,
            signature_date,
            created_by,
            updated_by,
            status
        )
        VALUES
        (
            dga_pif_tv_company_id,
            dga_pif_tv_contact_id,
            dga_pif_tv_production_id,
            dga_pif_tv_copyright_holder,
            dga_pif_tv_copyright_holder_name,
            dga_pif_tv_copyright_holder_phone,
            dga_pif_tv_writers,
            dga_pif_tv_budget,
            dga_pif_tv_locations,
            dga_pif_tv_date_pre_production,
            dga_pif_tv_date_principal_photography,
            dga_pif_tv_date_wrap,
            dga_pif_tv_format_multi_camera,
            dga_pif_tv_format_single_camera,
            dga_pif_tv_produced_digital,
            dga_pif_tv_produced_film,
            dga_pif_tv_produced_tape,
            dga_pif_tv_produced_live,
            dga_pif_tv_produced_other,
            dga_pif_tv_produced_other_description,
            dga_pif_tv_program_type_dramatic,
            dga_pif_tv_program_type_sitcom,
            dga_pif_tv_program_type_reality,
            dga_pif_tv_program_type_variety,
            dga_pif_tv_program_type_other,
            dga_pif_tv_program_type_other_description,
            dga_pif_tv_program_length_30,
            dga_pif_tv_program_length_60,
            dga_pif_tv_program_length_90,
            dga_pif_tv_program_length_120,
            dga_pif_tv_program_length_other,
            dga_pif_tv_program_length_other_description,
            dga_pif_tv_network,
            dga_pif_tv_network_abc,
            dga_pif_tv_network_cbs,
            dga_pif_tv_network_fox,
            dga_pif_tv_network_nbc,
            dga_pif_tv_network_pbs,
            dga_pif_tv_network_upn,
            dga_pif_tv_network_wb,
            dga_pif_tv_network_syndication,
            dga_pif_tv_network_syndication_description,
            dga_pif_tv_basic_cable,
            dga_pif_tv_basic_cable_a_and_e,
            dga_pif_tv_basic_cable_disney,
            dga_pif_tv_basic_cable_lifetime,
            dga_pif_tv_basic_cable_mtv,
            dga_pif_tv_basic_cable_nickelodeon,
            dga_pif_tv_basic_cable_tnt,
            dga_pif_tv_basic_cable_usa,
            dga_pif_tv_basic_cable_other,
            dga_pif_tv_basic_cable_other_description,
            dga_pif_tv_pay_tv,
            dga_pif_tv_pay_tv_hbo,
            dga_pif_tv_pay_tv_showtime,
            dga_pif_tv_pay_tv_tmc,
            dga_pif_tv_pay_tv_starz,
            dga_pif_tv_pay_tv_cinemax,
            dga_pif_tv_pay_tv_other,
            dga_pif_tv_pay_tv_other_description,
            dga_pif_tv_pilot,
            dga_pif_tv_direct_to_video,
            dga_pif_tv_other,
            dga_pif_tv_other_description,
            dga_pif_tv_employee_info_director_name,
            dga_pif_tv_employee_info_1_name,
            dga_pif_tv_employee_info_1_upm,
            dga_pif_tv_employee_info_1_associate_director,
            dga_pif_tv_employee_info_2_name,
            dga_pif_tv_employee_info_2_first_assistant_director,
            dga_pif_tv_employee_info_2_stage_manager,
            dga_pif_tv_employee_info_3_name,
            dga_pif_tv_employee_info_3_key_second_assistant_director,
            dga_pif_tv_employee_info_3_second_stage_manager,
            dga_pif_tv_employee_info_4_name,
            dga_pif_tv_employee_info_4_second_assistant_director,
            dga_pif_tv_employee_info_4_third_stage_manager,
            dga_pif_tv_employee_info_5_name,
            dga_pif_tv_employee_info_5_add_second_assistant_director,
            dga_pif_tv_employee_info_5_production_associate,
            dga_pif_tv_employee_info_6_name,
            dga_pif_tv_employee_info_6_associate_director,
            dga_pif_tv_employee_info_7_name,
            dga_pif_tv_employee_info_7_associate_director_line_cut,
            dga_pif_tv_employee_info_other_description,
            dga_pif_tv_affiliations_sav,
            dga_pif_tv_affiliations_wga,
            dga_pif_tv_affiliations_dcg,
            dga_pif_tv_affiliations_aftra,
            dga_pif_tv_affiliations_iatse,
            dga_pif_tv_affiliations_nabet,
            dga_pif_tv_affiliations_afm,
            dga_pif_tv_affiliations_actra,
            dga_pif_tv_affiliations_other,
            dga_pif_tv_affiliations_other_description,
            dga_pif_tv_employment_contact_name,
            dga_pif_tv_employment_contacr_phone,
            dga_pif_tv_residuals_contact_name,
            dga_pif_tv_residuals_contacr_phone,
            dga_pif_tv_primary_finance_source,
            dga_pif_tv_primary_finance_contact,
            dga_pif_tv_primary_finance_phone,
            dga_pif_tv_completion_bond_company,
            dga_pif_tv_completion_bond_contact,
            dga_pif_tv_completion_bond_phone,
            dga_pif_tv_payroll_company,
            dga_pif_tv_payroll_contact,
            dga_pif_tv_payroll_phone,
            dga_pif_tv_credit_line,
            dga_pif_tv_credit_line_bank,
            dga_pif_tv_credit_line_contact,
            dga_pif_tv_credit_line_phone,
            dga_pif_tv_foreign_distribuitors,
            dga_pif_tv_domestic_distribuitors,
            dga_pif_tv_signature,
            dga_pif_tv_signature_title,
            dga_pif_tv_signature_print_name,
            dga_pif_tv_signature_phone,
            dga_pif_tv_signature_date,
            dga_pif_tv_created_by,
            dga_pif_tv_updated_by,
            'CREATED'
        );

        SET return_value = LAST_INSERT_ID();
     END IF;

     IF (ROW_EXISTS >= 1) THEN
        UPDATE dga_pif_tv
           SET company_id                                    = dga_pif_tv_company_id,
               contact_id                                    = dga_pif_tv_contact_id,
               production_id                                 = dga_pif_tv_production_id,
               copyright_holder                              = dga_pif_tv_copyright_holder,
               copyright_holder_name                         = dga_pif_tv_copyright_holder_name,
               copyright_holder_phone                        = dga_pif_tv_copyright_holder_phone,
               writers                                       = dga_pif_tv_writers,
               budget                                        = dga_pif_tv_budget,
               locations                                     = dga_pif_tv_locations,
               date_pre_production                           = dga_pif_tv_date_pre_production,
               date_principal_photography                    = dga_pif_tv_date_principal_photography,
               date_wrap                                     = dga_pif_tv_date_wrap,
               format_multi_camera                           = dga_pif_tv_format_multi_camera,
               format_single_camera                          = dga_pif_tv_format_single_camera,
               produced_digital                              = dga_pif_tv_produced_digital,
               produced_film                                 = dga_pif_tv_produced_film,
               produced_tape                                 = dga_pif_tv_produced_tape,
               produced_live                                 = dga_pif_tv_produced_live,
               produced_other                                = dga_pif_tv_produced_other,
               produced_other_description                    = dga_pif_tv_produced_other_description,
               program_type_dramatic                         = dga_pif_tv_program_type_dramatic,
               program_type_sitcom                           = dga_pif_tv_program_type_sitcom,
               program_type_reality                          = dga_pif_tv_program_type_reality,
               program_type_variety                          = dga_pif_tv_program_type_variety,
               program_type_other                            = dga_pif_tv_program_type_other,
               program_type_other_description                = dga_pif_tv_program_type_other_description,
               program_length_30                             = dga_pif_tv_program_length_30,
               program_length_60                             = dga_pif_tv_program_length_60,
               program_length_90                             = dga_pif_tv_program_length_90,
               program_length_120                            = dga_pif_tv_program_length_120,
               program_length_other                          = dga_pif_tv_program_length_other,
               program_length_other_description              = dga_pif_tv_program_length_other_description,
               network                                       = dga_pif_tv_network,
               network_abc                                   = dga_pif_tv_network_abc,
               network_cbs                                   = dga_pif_tv_network_cbs,
               network_fox                                   = dga_pif_tv_network_fox,
               network_nbc                                   = dga_pif_tv_network_nbc,
               network_pbs                                   = dga_pif_tv_network_pbs,
               network_upn                                   = dga_pif_tv_network_upn,
               network_wb                                    = dga_pif_tv_network_wb,
               network_syndication                           = dga_pif_tv_network_syndication,
               network_syndication_description               = dga_pif_tv_network_syndication_description,
               basic_cable                                   = dga_pif_tv_basic_cable,
               basic_cable_a_and_e                           = dga_pif_tv_basic_cable_a_and_e,
               basic_cable_disney                            = dga_pif_tv_basic_cable_disney,
               basic_cable_lifetime                          = dga_pif_tv_basic_cable_lifetime,
               basic_cable_mtv                               = dga_pif_tv_basic_cable_mtv,
               basic_cable_nickelodeon                       = dga_pif_tv_basic_cable_nickelodeon,
               basic_cable_tnt                               = dga_pif_tv_basic_cable_tnt,
               basic_cable_usa                               = dga_pif_tv_basic_cable_usa,
               basic_cable_other                             = dga_pif_tv_basic_cable_other,
               basic_cable_other_description                 = dga_pif_tv_basic_cable_other_description,
               pay_tv                                        = dga_pif_tv_pay_tv,
               pay_tv_hbo                                    = dga_pif_tv_pay_tv_hbo,
               pay_tv_showtime                               = dga_pif_tv_pay_tv_showtime,
               pay_tv_tmc                                    = dga_pif_tv_pay_tv_tmc,
               pay_tv_starz                                  = dga_pif_tv_pay_tv_starz,
               pay_tv_cinemax                                = dga_pif_tv_pay_tv_cinemax,
               pay_tv_other                                  = dga_pif_tv_pay_tv_other,
               pay_tv_other_description                      = dga_pif_tv_pay_tv_other_description,
               pilot                                         = dga_pif_tv_pilot,
               direct_to_video                               = dga_pif_tv_direct_to_video,
               other                                         = dga_pif_tv_other,
               other_description                             = dga_pif_tv_other_description,
               employee_info_director_name                   = dga_pif_tv_employee_info_director_name,
               employee_info_1_name                          = dga_pif_tv_employee_info_1_name,
               employee_info_1_upm                           = dga_pif_tv_employee_info_1_upm,
               employee_info_1_associate_director            = dga_pif_tv_employee_info_1_associate_director,
               employee_info_2_name                          = dga_pif_tv_employee_info_2_name,
               employee_info_2_first_assistant_director      = dga_pif_tv_employee_info_2_first_assistant_director,
               employee_info_2_stage_manager                 = dga_pif_tv_employee_info_2_stage_manager,
               employee_info_3_name                          = dga_pif_tv_employee_info_3_name,
               employee_info_3_key_second_assistant_director = dga_pif_tv_employee_info_3_key_second_assistant_director,
               employee_info_3_second_stage_manager          = dga_pif_tv_employee_info_3_second_stage_manager,
               employee_info_4_name                          = dga_pif_tv_employee_info_4_name,
               employee_info_4_second_assistant_director     = dga_pif_tv_employee_info_4_second_assistant_director,
               employee_info_4_third_stage_manager           = dga_pif_tv_employee_info_4_third_stage_manager,
               employee_info_5_name                          = dga_pif_tv_employee_info_5_name,
               employee_info_5_add_second_assistant_director = dga_pif_tv_employee_info_5_add_second_assistant_director,
               employee_info_5_production_associate          = dga_pif_tv_employee_info_5_production_associate,
               employee_info_6_name                          = dga_pif_tv_employee_info_6_name,
               employee_info_6_associate_director            = dga_pif_tv_employee_info_6_associate_director,
               employee_info_7_name                          = dga_pif_tv_employee_info_7_name,
               employee_info_7_associate_director_line_cut   = dga_pif_tv_employee_info_7_associate_director_line_cut,
               employee_info_other_description               = dga_pif_tv_employee_info_other_description,
               affiliations_sav                              = dga_pif_tv_affiliations_sav,
               affiliations_wga                              = dga_pif_tv_affiliations_wga,
               affiliations_dcg                              = dga_pif_tv_affiliations_dcg,
               affiliations_aftra                            = dga_pif_tv_affiliations_aftra,
               affiliations_iatse                            = dga_pif_tv_affiliations_iatse,
               affiliations_nabet                            = dga_pif_tv_affiliations_nabet,
               affiliations_afm                              = dga_pif_tv_affiliations_afm,
               affiliations_actra                            = dga_pif_tv_affiliations_actra,
               affiliations_other                            = dga_pif_tv_affiliations_other,
               affiliations_other_description                = dga_pif_tv_affiliations_other_description,
               employment_contact_name                       = dga_pif_tv_employment_contact_name,
               employment_contacr_phone                      = dga_pif_tv_employment_contacr_phone,
               residuals_contact_name                        = dga_pif_tv_residuals_contact_name,
               residuals_contacr_phone                       = dga_pif_tv_residuals_contacr_phone,
               primary_finance_source                        = dga_pif_tv_primary_finance_source,
               primary_finance_contact                       = dga_pif_tv_primary_finance_contact,
               primary_finance_phone                         = dga_pif_tv_primary_finance_phone,
               completion_bond_company                       = dga_pif_tv_completion_bond_company,
               completion_bond_contact                       = dga_pif_tv_completion_bond_contact,
               completion_bond_phone                         = dga_pif_tv_completion_bond_phone,
               payroll_company                               = dga_pif_tv_payroll_company,
               payroll_contact                               = dga_pif_tv_payroll_contact,
               payroll_phone                                 = dga_pif_tv_payroll_phone,
               credit_line                                   = dga_pif_tv_credit_line,
               credit_line_bank                              = dga_pif_tv_credit_line_bank,
               credit_line_contact                           = dga_pif_tv_credit_line_contact,
               credit_line_phone                             = dga_pif_tv_credit_line_phone,
               foreign_distribuitors                         = dga_pif_tv_foreign_distribuitors,
               domestic_distribuitors                        = dga_pif_tv_domestic_distribuitors,
               signature                                     = dga_pif_tv_signature,
               signature_title                               = dga_pif_tv_signature_title,
               signature_print_name                          = dga_pif_tv_signature_print_name,
               signature_phone                               = dga_pif_tv_signature_phone,
               signature_date                                = dga_pif_tv_signature_date,
               created_by                                    = dga_pif_tv_created_by,
               updated_by                                    = dga_pif_tv_updated_by,
               status                                        = "UPDATED"
         WHERE id                                            = dga_pif_tv_id;
        SET return_value = dga_pif_tv_id;
     END IF;

     COMMIT;
END //
DELIMITER ;