DELIMITER //
CREATE PROCEDURE dga_director_scripted_deal_memo_set_list(
    IN  dga_director_scripted_deal_memo_id                                       INT,
    IN  dga_director_scripted_deal_memo_contact_id                               INT,
    IN  dga_director_scripted_deal_memo_ssn                                      VARCHAR(11),
    IN  dga_director_scripted_deal_memo_loanout                                  VARCHAR(30),
    IN  dga_director_scripted_deal_memo_fid                                      VARCHAR(30),
    IN  dga_director_scripted_deal_memo_salary                                   DECIMAL,
    IN  dga_director_scripted_deal_memo_salary_period_id                         INT,
    IN  dga_director_scripted_deal_memo_aditional_time                           DECIMAL,
    IN  dga_director_scripted_deal_memo_aditional_time_period_id                 INT,
    IN  dga_director_scripted_deal_memo_start_date                               DATE,
    IN  dga_director_scripted_deal_memo_guaranteed                               INT,
    IN  dga_director_scripted_deal_memo_guaranteed_period_id                     INT,
    IN  dga_director_scripted_deal_memo_dga_covered                              CHAR(1),
    IN  dga_director_scripted_deal_memo_addition_terms                           VARCHAR(1024),
    IN  dga_director_scripted_deal_memo_production_id                            INT,
    IN  dga_director_scripted_deal_memo_project_number                           VARCHAR(30),
    IN  dga_director_scripted_deal_memo_episode_id                               INT,
    IN  dga_director_scripted_deal_memo_episode_specific_length                  VARCHAR(50),
    IN  dga_director_scripted_deal_memo_segment                                  CHAR(1),
    IN  dga_director_scripted_deal_memo_segment_specific_length                  VARCHAR(50),
    IN  dga_director_scripted_deal_memo_length_30                                CHAR(1),
    IN  dga_director_scripted_deal_memo_length_60                                CHAR(1),
    IN  dga_director_scripted_deal_memo_length_90                                CHAR(1),
    IN  dga_director_scripted_deal_memo_length_120                               CHAR(1),
    IN  dga_director_scripted_deal_memo_length_other                             CHAR(1),
    IN  dga_director_scripted_deal_memo_pilot                                    CHAR(1),
    IN  dga_director_scripted_deal_memo_dramatic_basic_cable_budget              DECIMAL,
    IN  dga_director_scripted_deal_memo_type_production_multi_camera             CHAR(1),
    IN  dga_director_scripted_deal_memo_type_production_single_camera            CHAR(1),
    -- IN  dga_director_scripted_deal_memo_television_license_director    CHAR(1),
    -- IN  dga_director_scripted_deal_memo_television_license_budget      CHAR(1),
    IN  dga_director_scripted_deal_memo_produced_for_network                     CHAR(1),
    IN  dga_director_scripted_deal_memo_produced_for_non_network                 CHAR(1),
    IN  dga_director_scripted_deal_memo_produced_for_basic_cable                 CHAR(1),
    IN  dga_director_scripted_deal_memo_produced_for_pay_tv                      CHAR(1),
    IN  dga_director_scripted_deal_memo_produced_for_home_video                  CHAR(1),
    IN  dga_director_scripted_deal_memo_produced_non_network_prime_time          CHAR(1),
    IN  dga_director_scripted_deal_memo_produced_nnetwork_nprime_time            CHAR(1),
    IN  dga_director_scripted_deal_memo_project_budget_more                      CHAR(1),
    IN  dga_director_scripted_deal_memo_project_budget_less                      CHAR(1),
    IN  dga_director_scripted_deal_memo_second_unit_director                     CHAR(1),
    IN  dga_director_scripted_deal_memo_segment_applicable                       CHAR(1),
    IN  dga_director_scripted_deal_memo_individual_final_cut_authority           VARCHAR(50),
    IN  dga_director_scripted_deal_memo_other_conditions                         VARCHAR(50),
    IN  dga_director_scripted_deal_memo_employer_name                            VARCHAR(50),
    IN  dga_director_scripted_deal_memo_employee_name                            VARCHAR(50),
    IN  dga_director_scripted_deal_memo_employee_date                            DATE,
    IN  dga_director_scripted_deal_memo_signatory                                VARCHAR(50),
    IN  dga_director_scripted_deal_memo_signatory_by                             VARCHAR(50),
    IN  dga_director_scripted_deal_memo_signatory_date                           DATE,
    IN  dga_director_scripted_deal_memo_created_by                               VARCHAR(30),
    IN  dga_director_scripted_deal_memo_updated_by                               VARCHAR(30),
    IN  dga_director_scripted_deal_memo_status                                   VARCHAR(30),
    OUT return_value                                                             INTEGER
)
BEGIN
    DECLARE ROW_EXISTS INTEGER;

    SELECT COUNT(*)
      INTO ROW_EXISTS
      FROM dga_director_scripted_deal_memo
     WHERE id = dga_director_scripted_deal_memo_id;

     IF (ROW_EXISTS = 0) THEN
        INSERT INTO dga_director_scripted_deal_memo
        (
            contact_id,
            ssn,
            loanout,
            fid,
            salary,
            salary_period_id,
            aditional_time,
            aditional_time_period_id,
            start_date,
            guaranteed,
            guaranteed_period_id,
            dga_covered,
            addition_terms,
            production_id,
            project_number,
            episode_id,
            episode_specific_length,
            segment,
            segment_specific_length,
            length_30,
            length_60,
            length_90,
            length_120,
            length_other,
            pilot,
            dramatic_basic_cable_budget,
            type_production_multi_camera,
            type_production_single_camera,
            -- television_license_director,
            -- television_license_budget,
            produced_for_network,
            produced_for_non_network,
            produced_for_basic_cable,
            produced_for_pay_tv,
            produced_for_home_video,
            produced_non_network_prime_time,
            produced_non_network_non_prime_time,
            project_budget_more,
            project_budget_less,
            second_unit_director,
            segment_applicable,
            individual_final_cut_authority,
            other_conditions,
            employer_name,
            employee_name,
            employee_date,
            signatory,
            signatory_by,
            signatory_date,
            created_by,
            updated_by,
            status
        )
        VALUES
        (
            dga_director_scripted_deal_memo_contact_id,
            dga_director_scripted_deal_memo_ssn,
            dga_director_scripted_deal_memo_loanout,
            dga_director_scripted_deal_memo_fid,
            dga_director_scripted_deal_memo_salary,
            dga_director_scripted_deal_memo_salary_period_id,
            dga_director_scripted_deal_memo_aditional_time,
            dga_director_scripted_deal_memo_aditional_time_period_id,
            dga_director_scripted_deal_memo_start_date,
            dga_director_scripted_deal_memo_guaranteed,
            dga_director_scripted_deal_memo_guaranteed_period_id,
            dga_director_scripted_deal_memo_dga_covered,
            dga_director_scripted_deal_memo_addition_terms,
            dga_director_scripted_deal_memo_production_id,
            dga_director_scripted_deal_memo_project_number,
            dga_director_scripted_deal_memo_episode_id,
            dga_director_scripted_deal_memo_episode_specific_length,
            dga_director_scripted_deal_memo_segment,
            dga_director_scripted_deal_memo_segment_specific_length,
            dga_director_scripted_deal_memo_length_30,
            dga_director_scripted_deal_memo_length_60,
            dga_director_scripted_deal_memo_length_90,
            dga_director_scripted_deal_memo_length_120,
            dga_director_scripted_deal_memo_length_other,
            dga_director_scripted_deal_memo_pilot,
            dga_director_scripted_deal_memo_dramatic_basic_cable_budget,
            dga_director_scripted_deal_memo_type_production_multi_camera,
            dga_director_scripted_deal_memo_type_production_single_camera,
            -- dga_director_scripted_deal_memo_television_license_director,
            -- dga_director_scripted_deal_memo_television_license_budget,
            dga_director_scripted_deal_memo_produced_for_network,
            dga_director_scripted_deal_memo_produced_for_non_network,
            dga_director_scripted_deal_memo_produced_for_basic_cable,
            dga_director_scripted_deal_memo_produced_for_pay_tv,
            dga_director_scripted_deal_memo_produced_for_home_video,
            dga_director_scripted_deal_memo_produced_non_network_prime_time,
            dga_director_scripted_deal_memo_produced_nnetwork_nprime_time,
            dga_director_scripted_deal_memo_project_budget_more,
            dga_director_scripted_deal_memo_project_budget_less,
            dga_director_scripted_deal_memo_second_unit_director,
            dga_director_scripted_deal_memo_segment_applicable,
            dga_director_scripted_deal_memo_individual_final_cut_authority,
            dga_director_scripted_deal_memo_other_conditions,
            dga_director_scripted_deal_memo_employer_name,
            dga_director_scripted_deal_memo_employee_name,
            dga_director_scripted_deal_memo_employee_date,
            dga_director_scripted_deal_memo_signatory,
            dga_director_scripted_deal_memo_signatory_by,
            dga_director_scripted_deal_memo_signatory_date,
            dga_director_scripted_deal_memo_created_by,
            dga_director_scripted_deal_memo_updated_by,
            'CREATED'
        );

        SET return_value = LAST_INSERT_ID();
     END IF;

     IF (ROW_EXISTS >= 1) THEN
        UPDATE dga_director_scripted_deal_memo
           SET contact_id                            = dga_director_scripted_deal_memo_contact_id,
               ssn                                   = dga_director_scripted_deal_memo_ssn,
               loanout                               = dga_director_scripted_deal_memo_loanout,
               fid                                   = dga_director_scripted_deal_memo_fid,
               salary                                = dga_director_scripted_deal_memo_salary,
               salary_period_id                      = dga_director_scripted_deal_memo_salary_period_id,
               aditional_time                        = dga_director_scripted_deal_memo_aditional_time,
               aditional_time_period_id              = dga_director_scripted_deal_memo_aditional_time_period_id,
               start_date                            = dga_director_scripted_deal_memo_start_date,
               guaranteed                            = dga_director_scripted_deal_memo_guaranteed,
               guaranteed_period_id                  = dga_director_scripted_deal_memo_guaranteed_period_id,
               dga_covered                           = dga_director_scripted_deal_memo_dga_covered,
               addition_terms                        = dga_director_scripted_deal_memo_addition_terms,
               production_id                         = dga_director_scripted_deal_memo_production_id,
               project_number                        = dga_director_scripted_deal_memo_project_number,
               episode_id                            = dga_director_scripted_deal_memo_episode_id,
               episode_specific_length               = dga_director_scripted_deal_memo_episode_specific_length,
               segment                               = dga_director_scripted_deal_memo_segment,
               segment_specific_length               = dga_director_scripted_deal_memo_segment_specific_length,
               length_30                             = dga_director_scripted_deal_memo_length_30,
               length_60                             = dga_director_scripted_deal_memo_length_60,
               length_90                             = dga_director_scripted_deal_memo_length_90,
               length_120                            = dga_director_scripted_deal_memo_length_120,
               length_other                          = dga_director_scripted_deal_memo_length_other,
               pilot                                 = dga_director_scripted_deal_memo_pilot,
               dramatic_basic_cable_budget           = dga_director_scripted_deal_memo_dramatic_basic_cable_budget,
               type_production_multi_camera          = dga_director_scripted_deal_memo_type_production_multi_camera,
               type_production_single_camera         = dga_director_scripted_deal_memo_type_production_single_camera,
            --    television_license_director   = dga_director_scripted_deal_memo_television_license_director,
            --    television_license_budget     = dga_director_scripted_deal_memo_television_license_budget,
               produced_for_network                  = dga_director_scripted_deal_memo_produced_for_network,
               produced_for_non_network              = dga_director_scripted_deal_memo_produced_for_non_network,
               produced_for_basic_cable              = dga_director_scripted_deal_memo_produced_for_basic_cable,
               produced_for_pay_tv                   = dga_director_scripted_deal_memo_produced_for_pay_tv,
               produced_for_home_video               = dga_director_scripted_deal_memo_produced_for_home_video,
               produced_non_network_prime_time       = dga_director_scripted_deal_memo_produced_non_network_prime_time,
               produced_non_network_non_prime_time   = dga_director_scripted_deal_memo_produced_nnetwork_nprime_time,
               project_budget_more                   = dga_director_scripted_deal_memo_project_budget_more,
               project_budget_less                   = dga_director_scripted_deal_memo_project_budget_less,
               second_unit_director                  = dga_director_scripted_deal_memo_second_unit_director,
               segment_applicable                    = dga_director_scripted_deal_memo_segment_applicable,
               individual_final_cut_authority        = dga_director_scripted_deal_memo_individual_final_cut_authority,
               other_conditions                      = dga_director_scripted_deal_memo_other_conditions,
               employer_name                         = dga_director_scripted_deal_memo_employer_name,
               employee_name                         = dga_director_scripted_deal_memo_employee_name,
               employee_date                         = dga_director_scripted_deal_memo_employee_date,
               signatory                             = dga_director_scripted_deal_memo_signatory,
               signatory_by                          = dga_director_scripted_deal_memo_signatory_by,
               signatory_date                        = dga_director_scripted_deal_memo_signatory_date,
               created                               = dga_director_scripted_deal_memo_created,
               created_by                            = dga_director_scripted_deal_memo_created_by,
               updated                               = dga_director_scripted_deal_memo_updated,
               updated_by                            = dga_director_scripted_deal_memo_updated_by,
               status                                = 'UPDATED'
         WHERE id                                    = dga_director_scripted_deal_memo_id;

         SET return_value = dga_director_scripted_deal_memo_id;
     END IF;

     COMMIT;
END //
DELIMITER ;