DELIMITER //
CREATE PROCEDURE dga_employment_data_set_list(
    IN  dga_employment_data_id                                  INT,
    IN  dga_employment_data_report_date                         DATE,
    IN  dga_employment_data_prepared_by                         VARCHAR(50),
    IN  dga_employment_data_quarter                             VARCHAR(10),
    IN  dga_employment_data_year                                YEAR,
    IN  dga_employment_data_company_id                          INT,
    IN  dga_employment_data_production_id                       INT,
    IN  dga_employment_data_director_name                       VARCHAR(50),
    IN  dga_employment_data_director_first_number               INT,
    IN  dga_employment_data_director_gender                     CHAR(1),
    IN  dga_employment_data_director_caucasion                  CHAR(1),
    IN  dga_employment_data_director_afro_american              CHAR(1),
    IN  dga_employment_data_director_latino                     CHAR(1),
    IN  dga_employment_data_director_asian                      CHAR(1),
    IN  dga_employment_data_director_native                     CHAR(1),
    IN  dga_employment_data_director_unknown                    CHAR(1),
    IN  dga_employment_data_unit_production_name                VARCHAR(50),
    IN  dga_employment_data_unit_production_gender              CHAR(1),
    IN  dga_employment_data_unit_production_caucasion           CHAR(1),
    IN  dga_employment_data_unit_production_afro_american       CHAR(1),
    IN  dga_employment_data_unit_production_latino              CHAR(1),
    IN  dga_employment_data_unit_production_asian               CHAR(1),
    IN  dga_employment_data_unit_production_native              CHAR(1),
    IN  dga_employment_data_unit_production_unknown             CHAR(1),
    IN  dga_employment_data_first_assistant_name                VARCHAR(50),
    IN  dga_employment_data_first_assistant_gender              CHAR(1),
    IN  dga_employment_data_first_assistant_caucasion           CHAR(1),
    IN  dga_employment_data_first_assistant_afro_american       CHAR(1),
    IN  dga_employment_data_first_assistant_latino              CHAR(1),
    IN  dga_employment_data_first_assistant_asian               CHAR(1),
    IN  dga_employment_data_first_assistant_native              CHAR(1),
    IN  dga_employment_data_first_assistant_unknown             CHAR(1),
    IN  dga_employment_data_second_assistant_name               VARCHAR(50),
    IN  dga_employment_data_second_assistant_gender             CHAR(1),
    IN  dga_employment_data_second_assistant_caucasion          CHAR(1),
    IN  dga_employment_data_second_assistant_afro_american      CHAR(1),
    IN  dga_employment_data_second_assistant_latino             CHAR(1),
    IN  dga_employment_data_second_assistant_asian              CHAR(1),
    IN  dga_employment_data_second_assistant_native             CHAR(1),
    IN  dga_employment_data_second_assistant_unknown            CHAR(1),
    IN  dga_employment_data_technical_coordinator_name          VARCHAR(50),
    IN  dga_employment_data_technical_coordinator_gender        CHAR(1),
    IN  dga_employment_data_technical_coordinator_caucasion     CHAR(1),
    IN  dga_employment_data_technical_coordinator_afro_american CHAR(1),
    IN  dga_employment_data_technical_coordinator_latino        CHAR(1),
    IN  dga_employment_data_technical_coordinator_asian         CHAR(1),
    IN  dga_employment_data_technical_coordinator_native        CHAR(1),
    IN  dga_employment_data_technical_coordinator_unknown       CHAR(1),
    IN  dga_employment_data_associate_director_name             VARCHAR(50),
    IN  dga_employment_data_associate_director_gender           CHAR(1),
    IN  dga_employment_data_associate_director_caucasion        CHAR(1),
    IN  dga_employment_data_associate_director_afro_american    CHAR(1),
    IN  dga_employment_data_associate_director_latino           CHAR(1),
    IN  dga_employment_data_associate_director_asian            CHAR(1),
    IN  dga_employment_data_associate_director_native           CHAR(1),
    IN  dga_employment_data_associate_director_unknown          CHAR(1),
    IN  dga_employment_data_stage_manager_name                  VARCHAR(50),
    IN  dga_employment_data_stage_manager_gender                CHAR(1),
    IN  dga_employment_data_stage_manager_caucasion             CHAR(1),
    IN  dga_employment_data_stage_manager_afro_american         CHAR(1),
    IN  dga_employment_data_stage_manager_latino                CHAR(1),
    IN  dga_employment_data_stage_manager_asian                 CHAR(1),
    IN  dga_employment_data_stage_manager_native                CHAR(1),
    IN  dga_employment_data_stage_manager_unknown               CHAR(1),
    IN  dga_employment_data_created_by                          VARCHAR(30),
    IN  dga_employment_data_updated_by                          VARCHAR(30),
    OUT return_value                                            INTEGER
)
BEGIN
    DECLARE ROW_EXISTS INTEGER;

    SELECT COUNT(*)
      INTO ROW_EXISTS
      FROM dga_employment_data
     WHERE id = dga_employment_data_id;

     IF (ROW_EXISTS = 0) THEN
        INSERT INTO dga_employment_data
        (
            report_date,
            prepared_by,
            quarter,
            year,
            company_id,
            production_id,
            director_name,
            director_first_number,
            director_gender,
            director_caucasion,
            director_afro_american,
            director_latino,
            director_asian,
            director_native,
            director_unknown,
            unit_production_name,
            unit_production_gender,
            unit_production_caucasion,
            unit_production_afro_american,
            unit_production_latino,
            unit_production_asian,
            unit_production_native,
            unit_production_unknown,
            first_assistant_name,
            first_assistant_gender,
            first_assistant_caucasion,
            first_assistant_afro_american,
            first_assistant_latino,
            first_assistant_asian,
            first_assistant_native,
            first_assistant_unknown,
            second_assistant_name,
            second_assistant_gender,
            second_assistant_caucasion,
            second_assistant_afro_american,
            second_assistant_latino,
            second_assistant_asian,
            second_assistant_native,
            second_assistant_unknown,
            technical_coordinator_name,
            technical_coordinator_gender,
            technical_coordinator_caucasion,
            technical_coordinator_afro_american,
            technical_coordinator_latino,
            technical_coordinator_asian,
            technical_coordinator_native,
            technical_coordinator_unknown,
            associate_director_name,
            associate_director_gender,
            associate_director_caucasion,
            associate_director_afro_american,
            associate_director_latino,
            associate_director_asian,
            associate_director_native,
            associate_director_unknown,
            stage_manager_name,
            stage_manager_gender,
            stage_manager_caucasion,
            stage_manager_afro_american,
            stage_manager_latino,
            stage_manager_asian,
            stage_manager_native,
            stage_manager_unknown,
            created_by,
            updated_by,
            status
        )
        VALUES
        (
            dga_employment_data_report_date,
            dga_employment_data_prepared_by,
            dga_employment_data_quarter,
            dga_employment_data_year,
            dga_employment_data_company_id,
            dga_employment_data_production_id,
            dga_employment_data_director_name,
            dga_employment_data_director_first_number,
            dga_employment_data_director_gender,
            dga_employment_data_director_caucasion,
            dga_employment_data_director_afro_american,
            dga_employment_data_director_latino,
            dga_employment_data_director_asian,
            dga_employment_data_director_native,
            dga_employment_data_director_unknown,
            dga_employment_data_unit_production_name,
            dga_employment_data_unit_production_gender,
            dga_employment_data_unit_production_caucasion,
            dga_employment_data_unit_production_afro_american,
            dga_employment_data_unit_production_latino,
            dga_employment_data_unit_production_asian,
            dga_employment_data_unit_production_native,
            dga_employment_data_unit_production_unknown,
            dga_employment_data_first_assistant_name,
            dga_employment_data_first_assistant_gender,
            dga_employment_data_first_assistant_caucasion,
            dga_employment_data_first_assistant_afro_american,
            dga_employment_data_first_assistant_latino,
            dga_employment_data_first_assistant_asian,
            dga_employment_data_first_assistant_native,
            dga_employment_data_first_assistant_unknown,
            dga_employment_data_second_assistant_name,
            dga_employment_data_second_assistant_gender,
            dga_employment_data_second_assistant_caucasion,
            dga_employment_data_second_assistant_afro_american,
            dga_employment_data_second_assistant_latino,
            dga_employment_data_second_assistant_asian,
            dga_employment_data_second_assistant_native,
            dga_employment_data_second_assistant_unknown,
            dga_employment_data_technical_coordinator_name,
            dga_employment_data_technical_coordinator_gender,
            dga_employment_data_technical_coordinator_caucasion,
            dga_employment_data_technical_coordinator_afro_american,
            dga_employment_data_technical_coordinator_latino,
            dga_employment_data_technical_coordinator_asian,
            dga_employment_data_technical_coordinator_native,
            dga_employment_data_technical_coordinator_unknown,
            dga_employment_data_associate_director_name,
            dga_employment_data_associate_director_gender,
            dga_employment_data_associate_director_caucasion,
            dga_employment_data_associate_director_afro_american,
            dga_employment_data_associate_director_latino,
            dga_employment_data_associate_director_asian,
            dga_employment_data_associate_director_native,
            dga_employment_data_associate_director_unknown,
            dga_employment_data_stage_manager_name,
            dga_employment_data_stage_manager_gender,
            dga_employment_data_stage_manager_caucasion,
            dga_employment_data_stage_manager_afro_american,
            dga_employment_data_stage_manager_latino,
            dga_employment_data_stage_manager_asian,
            dga_employment_data_stage_manager_native,
            dga_employment_data_stage_manager_unknown,
            dga_employment_data_created_by,
            dga_employment_data_updated_by,
            'CREATED'
        );

        SET return_value = LAST_INSERT_ID();
     END IF;

     IF (ROW_EXISTS >= 1) THEN
        UPDATE dga_employment_data
           SET report_date                          = dga_employment_data_report_date,
               prepared_by                          = dga_employment_data_prepared_by,
               quarter                              = dga_employment_data_quarter,
               year                                 = dga_employment_data_year,
               company_id                           = dga_employment_data_company_id,
               production_id                        = dga_employment_data_production_id,
               director_name                        = dga_employment_data_director_name,
               director_first_number                = dga_employment_data_director_first_number,
               director_gender                      = dga_employment_data_director_gender,
               director_caucasion                   = dga_employment_data_director_caucasion,
               director_afro_american               = dga_employment_data_director_afro_american,
               director_latino                      = dga_employment_data_director_latino,
               director_asian                       = dga_employment_data_director_asian,
               director_native                      = dga_employment_data_director_native,
               director_unknown                     = dga_employment_data_director_unknown,
               unit_production_name                 = dga_employment_data_unit_production_name,
               unit_production_gender               = dga_employment_data_unit_production_gender,
               unit_production_caucasion            = dga_employment_data_unit_production_caucasion,
               unit_production_afro_american        = dga_employment_data_unit_production_afro_american,
               unit_production_latino               = dga_employment_data_unit_production_latino,
               unit_production_asian                = dga_employment_data_unit_production_asian,
               unit_production_native               = dga_employment_data_unit_production_native,
               unit_production_unknown              = dga_employment_data_unit_production_unknown,
               first_assistant_name                 = dga_employment_data_first_assistant_name,
               first_assistant_gender               = dga_employment_data_first_assistant_gender,
               first_assistant_caucasion            = dga_employment_data_first_assistant_caucasion,
               first_assistant_afro_american        = dga_employment_data_first_assistant_afro_american,
               first_assistant_latino               = dga_employment_data_first_assistant_latino,
               first_assistant_asian                = dga_employment_data_first_assistant_asian,
               first_assistant_native               = dga_employment_data_first_assistant_native,
               first_assistant_unknown              = dga_employment_data_first_assistant_unknown,
               second_assistant_name                = dga_employment_data_second_assistant_name,
               second_assistant_gender              = dga_employment_data_second_assistant_gender,
               second_assistant_caucasion           = dga_employment_data_second_assistant_caucasion,
               second_assistant_afro_american       = dga_employment_data_second_assistant_afro_american,
               second_assistant_latino              = dga_employment_data_second_assistant_latino,
               second_assistant_asian               = dga_employment_data_second_assistant_asian,
               second_assistant_native              = dga_employment_data_second_assistant_native,
               second_assistant_unknown             = dga_employment_data_second_assistant_unknown,
               technical_coordinator_name           = dga_employment_data_technical_coordinator_name,
               technical_coordinator_gender         = dga_employment_data_technical_coordinator_gender,
               technical_coordinator_caucasion      = dga_employment_data_technical_coordinator_caucasion,
               technical_coordinator_afro_american  = dga_employment_data_technical_coordinator_afro_american,
               technical_coordinator_latino         = dga_employment_data_technical_coordinator_latino,
               technical_coordinator_asian          = dga_employment_data_technical_coordinator_asian,
               technical_coordinator_native         = dga_employment_data_technical_coordinator_native,
               technical_coordinator_unknown        = dga_employment_data_technical_coordinator_unknown,
               associate_director_name              = dga_employment_data_director_assistant_name,
               associate_director_gender            = dga_employment_data_director_assistant_gender,
               associate_director_caucasion         = dga_employment_data_director_assistant_caucasion,
               associate_director_afro_american     = dga_employment_data_director_assistant_afro_american,
               associate_director_latino            = dga_employment_data_director_assistant_latino,
               associate_director_asian             = dga_employment_data_director_assistant_asian,
               associate_director_native            = dga_employment_data_director_assistant_native,
               associate_director_unknown           = dga_employment_data_director_assistant_unknown,
               stage_manager_name                   = dga_employment_data_stage_manager_name,
               stage_manager_gender                 = dga_employment_data_stage_manager_gender,
               stage_manager_caucasion              = dga_employment_data_stage_manager_caucasion,
               stage_manager_afro_american          = dga_employment_data_stage_manager_afro_american,
               stage_manager_latino                 = dga_employment_data_stage_manager_latino,
               stage_manager_asian                  = dga_employment_data_stage_manager_asian,
               stage_manager_native                 = dga_employment_data_stage_manager_native,
               stage_manager_unknown                = dga_employment_data_stage_manager_unknown,
               updated_by                           = dga_employment_data_updated_by,
               status                               = 'UPDATED'
         WHERE id =    dga_employment_data_id;

         SET return_value = dga_employment_data_id;
     END IF;

     COMMIT;
END //
DELIMITER ;