CREATE TABLE contact(
    id                   INTEGER      NOT NULL AUTO_INCREMENT,
    first_name           VARCHAR(50)  NOT NULL,
    middle_name          VARCHAR(50),
    last_name            VARCHAR(50)  NOT NULL,
    suffix               VARCHAR(50),
    address              VARCHAR(100),
    city                 VARCHAR(100),
    state_code           CHAR(2),
    phone                VARCHAR(20),
    email                VARCHAR(100),
    ssn                  VARCHAR(11),
    website              VARCHAR(100),
    picture_path         VARCHAR(120),
    created              TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    created_by           VARCHAR(30),
    updated              TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by           VARCHAR(30),
    status               VARCHAR(30),
    CONSTRAINT pk_contact_id    PRIMARY KEY (id),
    CONSTRAINT fk_contact_state FOREIGN KEY (state_code) REFERENCES state (CODE)
) ENGINE = InnoDB;