CREATE TABLE dga_employment_data(
    id                                     INTEGER      NOT NULL AUTO_INCREMENT,
    report_date                            DATE         NOT NULL,
    prepared_by                            VARCHAR(50)  NOT NULL,
    quarter                                VARCHAR(10)  NOT NULL,
    year                                   YEAR         NOT NULL,
    company_id                             INTEGER      NOT NULL,
    production_id                          INTEGER      NOT NULL,
    director_name                          VARCHAR(50),
    director_first_number                  INTEGER,
    director_gender                        CHAR(1),
    director_caucasion                     CHAR(1),
    director_afro_american                 CHAR(1),
    director_latino                        CHAR(1),
    director_asian                         CHAR(1),
    director_native                        CHAR(1),
    director_unknown                       CHAR(1),
    unit_production_name                   VARCHAR(50),
    unit_production_gender                 CHAR(1),
    unit_production_caucasion              CHAR(1),
    unit_production_afro_american          CHAR(1),
    unit_production_latino                 CHAR(1),
    unit_production_asian                  CHAR(1),
    unit_production_native                 CHAR(1),
    unit_production_unknown                CHAR(1),
    first_assistant_name                   VARCHAR(50),
    first_assistant_gender                 CHAR(1),
    first_assistant_caucasion              CHAR(1),
    first_assistant_afro_american          CHAR(1),
    first_assistant_latino                 CHAR(1),
    first_assistant_asian                  CHAR(1),
    first_assistant_native                 CHAR(1),
    first_assistant_unknown                CHAR(1),
    second_assistant_name                  VARCHAR(50),
    second_assistant_gender                CHAR(1),
    second_assistant_caucasion             CHAR(1),
    second_assistant_afro_american         CHAR(1),
    second_assistant_latino                CHAR(1),
    second_assistant_asian                 CHAR(1),
    second_assistant_native                CHAR(1),
    second_assistant_unknown               CHAR(1),
    associate_assistant_name               VARCHAR(50),
    associate_assistant_gender             CHAR(1),
    associate_assistant_caucasion          CHAR(1),
    associate_assistant_afro_american      CHAR(1),
    associate_assistant_latino             CHAR(1),
    associate_assistant_asian              CHAR(1),
    associate_assistant_native             CHAR(1),
    associate_assistant_unknown            CHAR(1),
    stage_assistant_name                   VARCHAR(50),
    stage_assistant_gender                 CHAR(1),
    stage_assistant_caucasion              CHAR(1),
    stage_assistant_afro_american          CHAR(1),
    stage_assistant_latino                 CHAR(1),
    stage_assistant_asian                  CHAR(1),
    stage_assistant_native                 CHAR(1),
    stage_assistant_unknown                CHAR(1),
    created                                TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    created_by                             VARCHAR(30),
    updated                                TIMESTAMP   DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by                             VARCHAR(30),
    status                                 VARCHAR(30),
    CONSTRAINT pk_dga_employment_data_id         PRIMARY KEY (id),
    CONSTRAINT fk_dga_employment_data_company    FOREIGN KEY (company_id)    REFERENCES company    (id),
    CONSTRAINT fk_dga_employment_data_production FOREIGN KEY (production_id) REFERENCES production (id)
) ENGINE = InnoDB;