CREATE TABLE location(
    id                   INTEGER      NOT NULL AUTO_INCREMENT,
    name                 VARCHAR(50)  NOT NULL,
    location_type_id     INTEGER      NOT NULL,
    address              VARCHAR(100),
    city                 VARCHAR(100),
    state_code           CHAR(2),
    zipcode              VARCHAR(10),
    phone                VARCHAR(20),
    latitude             DOUBLE(11,8) NOT NULL,
    longitude            DOUBLE(11,8) NOT NULL,
    contact_city         VARCHAR(100),
    contact_state_code   CHAR(2),
    contact_zipcode      VARCHAR(10),
    contact_phone        VARCHAR(20),
    contact_email        VARCHAR(100),
    contact_website      VARCHAR(100),
    created              TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    created_by           VARCHAR(30),
    updated              TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by           VARCHAR(30),
    status               VARCHAR(30),
    CONSTRAINT pk_location_id               PRIMARY KEY (id),
    CONSTRAINT fk_location_location_type_id FOREIGN KEY (location_type_id)   REFERENCES location_type (id),
    CONSTRAINT fk_location_state            FOREIGN KEY (state_code)         REFERENCES state (code),
    CONSTRAINT fk_location_contact_state    FOREIGN KEY (contact_state_code) REFERENCES state (code)
) ENGINE = InnoDB;