CREATE TABLE sav_final_cast_list_info_item(
    id                               INTEGER      NOT NULL AUTO_INCREMENT,
    sav_final_cast_list_info_id      INT          NOT NULL,
    production_id                    INT          NOT NULL,
    contact_id                       INT          NOT NULL,
    loan_out_corp                    VARCHAR(50),
    federal_id                       VARCHAR(30),
    days_number                      INT,
    weeks_number                     INT,
    start_date                       DATE,
    end_date                         DATE,
    contract_type                    CHAR(1),
    sav_performer_type_id            INT NOT NULL,
    salary_total_gross               NUMERIC(15,2)  NOT NULL DEFAULT 0.00,
    salary_base                      NUMERIC(15,2)  NOT NULL DEFAULT 0.00,
    units_type                       INT,
    units_salary                     INT,
    units_total                      INT,
    created                          TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    created_by                       VARCHAR(30),
    updated                          TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by                       VARCHAR(30),
    status                           VARCHAR(30),
    CONSTRAINT pk_sav_final_cast_list_info_item_id                       PRIMARY KEY (id),
    CONSTRAINT fk_sav_final_cast_list_info_item_sav_final_cast_list_info FOREIGN KEY (sav_final_cast_list_info_id) REFERENCES sav_final_cast_list_info (id),
    CONSTRAINT fk_sav_final_cast_list_contact                            FOREIGN KEY (contact_id)                  REFERENCES contact                  (id),
    CONSTRAINT fk_sav_final_cast_list_production_contact                 FOREIGN KEY (production_id, contact_id)   REFERENCES production_contact       (production_id, contact_id),
    CONSTRAINT fk_sav_final_cast_list_sav_performer_type                 FOREIGN KEY (sav_performer_type_id)       REFERENCES sav_performer_type       (id)
) ENGINE = InnoDB;