CREATE TABLE subaccount(
    id                   INTEGER      NOT NULL AUTO_INCREMENT,
    code                 CHAR(10)     NOT NULL,
    title                VARCHAR(50)  NOT NULL,
    media_company_id     INTEGER      NOT NULL,
    business_group_id    INTEGER      NOT NULL,
    network_id           INTEGER      NOT NULL,
    production_id        INTEGER      NOT NULL,
    season_id            INTEGER,
    episode_id           INTEGER,
    ledger_id            INTEGER      NOT NULL,
    account_id           INTEGER      NOT NULL,
    created              TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    created_by           VARCHAR(30),
    updated              TIMESTAMP   DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by           VARCHAR(30),
    status               VARCHAR(30),
    CONSTRAINT pk_subaccount_id             PRIMARY KEY (id),
    CONSTRAINT fk_subaccount_media_company  FOREIGN KEY (media_company_id)  REFERENCES company        (id),
    CONSTRAINT fk_subaccount_business_group FOREIGN KEY (business_group_id) REFERENCES business_group (id),
    CONSTRAINT fk_subaccount_network        FOREIGN KEY (network_id)        REFERENCES network        (id),
    CONSTRAINT fk_subaccount_production     FOREIGN KEY (production_id)     REFERENCES production     (id),
    CONSTRAINT fk_subaccount_season         FOREIGN KEY (season_id)         REFERENCES season         (id),
    CONSTRAINT fk_subaccount_episode        FOREIGN KEY (episode_id)        REFERENCES episode        (id),
    CONSTRAINT fk_subaccount_ledger         FOREIGN KEY (ledger_id)         REFERENCES ledger         (id),
    CONSTRAINT fk_subaccount_account        FOREIGN KEY (account_id)        REFERENCES account        (id)
) ENGINE = InnoDB;