CREATE TABLE transaction(
    id                   INTEGER        NOT NULL AUTO_INCREMENT,
    media_company_id     INTEGER        NOT NULL,
    business_group_id    INTEGER        NOT NULL,
    network_id           INTEGER        NOT NULL,
    production_id        INTEGER        NOT NULL,
    season_id            INTEGER,
    episode_id           INTEGER,
    ledger_id            INTEGER        NOT NULL,
    account_id           INTEGER        NOT NULL,
    subaccount_id        INTEGER        NOT NULL,
    description          VARCHAR(50)    NOT NULL,
    budget               NUMERIC(15,2)  NOT NULL DEFAULT 0.00,
    total_budget         NUMERIC(15,2)  NOT NULL DEFAULT 0.00,
    guarantee            INTEGER        NOT NULL DEFAULT 0,
    period_id            INTEGER        NOT NULL,
    actual               NUMERIC(15,2)  NOT NULL DEFAULT 0.00,
    total_actual         NUMERIC(15,2)  NOT NULL DEFAULT 0.00,
    comment              VARCHAR(255),
    created              TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    created_by           VARCHAR(30),
    updated              TIMESTAMP   DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by           VARCHAR(30),
    status               VARCHAR(30),
    CONSTRAINT pk_transaction_id             PRIMARY KEY (id),
    CONSTRAINT fk_transaction_media_company  FOREIGN KEY (media_company_id)  REFERENCES company        (id),
    CONSTRAINT fk_transaction_business_group FOREIGN KEY (business_group_id) REFERENCES business_group (id),
    CONSTRAINT fk_transaction_network        FOREIGN KEY (network_id)        REFERENCES network        (id),
    CONSTRAINT fk_transaction_production     FOREIGN KEY (production_id)     REFERENCES production     (id),
    CONSTRAINT fk_transaction_season         FOREIGN KEY (season_id)         REFERENCES season         (id),
    CONSTRAINT fk_transaction_episode        FOREIGN KEY (episode_id)        REFERENCES episode        (id),
    CONSTRAINT fk_transaction_ledger         FOREIGN KEY (ledger_id)         REFERENCES ledger         (id),
    CONSTRAINT fk_transaction_account        FOREIGN KEY (account_id)        REFERENCES account        (id),
    CONSTRAINT fk_transaction_subaccount     FOREIGN KEY (subaccount_id)     REFERENCES subaccount     (id),
    CONSTRAINT fk_transaction_period         FOREIGN KEY (period_id)         REFERENCES period         (id)
) ENGINE = InnoDB;