CREATE TABLE wga_work_list_item(
    id                   INTEGER      NOT NULL AUTO_INCREMENT,
    wga_work_list_id     INTEGER      NOT NULL,
    contact_id           INTEGER      NOT NULL,
    episode_id           INTEGER      NOT NULL,
    deal_type_id         INTEGER      NOT NULL,
    field_of_work_id     INTEGER      NOT NULL,
    date_start           DATE,
    date_end             DATE,
    additional_data      VARCHAR(100),
    created              TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    created_by           VARCHAR(30),
    updated              TIMESTAMP   DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by           VARCHAR(30),
    status               VARCHAR(30),
    CONSTRAINT pk_wga_work_list_item_id                 PRIMARY KEY (id),
    CONSTRAINT fk_wga_work_list_item_wga_work_list_item FOREIGN KEY (wga_work_list_id) REFERENCES wga_work_list     (id),
    CONSTRAINT fk_wga_work_list_item_contact            FOREIGN KEY (contact_id)       REFERENCES contact           (id),
    CONSTRAINT fk_wga_work_list_item_episode            FOREIGN KEy (episode_id)       REFERENCES episode           (id),
    CONSTRAINT fk_wga_work_list_item_wga_deal_type      FOREIGN KEY (deal_type_id)     REFERENCES wga_deal_type     (id),
    CONSTRAINT fk_wga_work_list_item_wga_field_of_work  FOREIGN KEY (field_of_work_id) REFERENCES wga_field_of_work (id)
) ENGINE = InnoDB;