CREATE TABLE wga_ntwc(
    id                                      INTEGER     NOT NULL AUTO_INCREMENT,
    date                                    DATE        NOT NULL,
    production_id                           INTEGER     NOT NULL,
    production_number                       VARCHAR(30) NOT NULL,
    episode_id                              INTEGER     NOT NULL,
    pilot                                   CHAR(1)  DEFAULT 'F',
    pilot_network_id                        INTEGER,
    pilot_production_lenght_id              INTEGER,
    executive_producer_contact_id           INTEGER NOT NULL,
    director_contact_id                     INTEGER NOT NULL,
    story_editor_contact_id                 INTEGER NOT NULL,
    other_executive_producer_contact_id     INTEGER,
    producer_contact_id                     INTEGER,
    supervising_producer_contact_id         INTEGER,
    sent_to_writers                         DATE    NOT NULL,
    protest_communicated                    DATE    NOT NULL,
    by_contact_id                           INTEGER,
    created                                 TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    created_by                              VARCHAR(30),
    updated                                 TIMESTAMP   DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by                              VARCHAR(30),
    status                                  VARCHAR(30),
    CONSTRAINT pk_wga_ntwc_id                                          PRIMARY KEY (id),
    CONSTRAINT fk_wga_ntwc_production                                  FOREIGN KEY (production_id)                                      REFERENCES production        (id),
    CONSTRAINT fk_wga_ntwc_episode                                     FOREIGN KEY (episode_id)                                         REFERENCES episode           (id),
    CONSTRAINT fk_wga_ntwc_network                                     FOREIGN KEY (pilot_network_id)                                   REFERENCES network           (id),
    CONSTRAINT fk_wga_ntwc_production_length                           FOREIGN KEY (pilot_production_lenght_id)                         REFERENCES production_length (id),
    CONSTRAINT fk_wga_ntwc_executive_producer_contact                  FOREIGN KEY (executive_producer_contact_id)                      REFERENCES contact           (id),
    CONSTRAINT fk_wga_ntwc_executive_producer_production_contact       FOREIGN KEY (production_id, executive_producer_contact_id)       REFERENCES production_contact (production_id, contact_id),
    CONSTRAINT fk_wga_ntwc_director_contact                            FOREIGN KEY (director_contact_id)                                REFERENCES contact           (id),
    CONSTRAINT fk_wga_ntwc_director_production_contact                 FOREIGN KEY (production_id, director_contact_id)                 REFERENCES production_contact (production_id, contact_id),
    CONSTRAINT fk_wga_ntwc_story_editor_contact                        FOREIGN KEY (story_editor_contact_id)                            REFERENCES contact           (id),
    CONSTRAINT fk_wga_ntwc_story_editor_production_contact             FOREIGN KEY (production_id, story_editor_contact_id)             REFERENCES production_contact (production_id, contact_id),
    CONSTRAINT fk_wga_ntwc_other_executive_producer_contact            FOREIGN KEY (other_executive_producer_contact_id)                REFERENCES contact           (id),
    CONSTRAINT fk_wga_ntwc_other_executive_producer_production_contact FOREIGN KEY (production_id, other_executive_producer_contact_id) REFERENCES production_contact (production_id, contact_id),
    CONSTRAINT fk_wga_ntwc_producer_contact                            FOREIGN KEY (producer_contact_id)                                REFERENCES contact           (id),
    CONSTRAINT fk_wga_ntwc_producer_production_contact                 FOREIGN KEY (production_id, producer_contact_id)                 REFERENCES production_contact (production_id, contact_id),
    CONSTRAINT fk_wga_ntwc_supervising_producer_contact                FOREIGN KEY (supervising_producer_contact_id)                    REFERENCES contact           (id),
    CONSTRAINT fk_wga_ntwc_supervising_producer_production_contact     FOREIGN KEY (production_id, supervising_producer_contact_id)     REFERENCES production_contact (production_id, contact_id),
    CONSTRAINT fk_wga_ntwc_by_contact                                  FOREIGN KEY (by_contact_id)                                      REFERENCES contact           (id),
    CONSTRAINT fk_wga_ntwc_by_production_contact                       FOREIGN KEY (production_id, by_contact_id)                       REFERENCES production_contact (production_id, contact_id)
) ENGINE = InnoDB;